import { run } from './src/index.js';
const cases = [
 ['functor both vars','functor(_,_,0)','instantiation_error'],
 ['functor term arity vars','functor(_,a,_)','instantiation_error'],
 ['functor name type','functor(_,f(a),0)','type_error(atomic)'],
 ['functor arity type','functor(_,a,a)','type_error(integer)'],
 ['functor numeric name positive arity','functor(_,1,1)','type_error(atom)'],
 ['functor negative arity','functor(_,a,-1)','domain_error(not_less_than_zero)'],
 ['arg n var','arg(_,f(a),_)','instantiation_error'],
 ['arg term var','arg(1,_,_)','instantiation_error'],
 ['arg n type','arg(a,f(a),_)','type_error(integer)'],
 ['arg term atomic','arg(1,a,_)','type_error(compound)'],
 ['arg negative','arg(-1,f(a),_)','domain_error(not_less_than_zero)'],
 ['univ partial','_ =.. [f|_]','instantiation_error'],
 ['univ nonlist','_ =.. foo','type_error(list)'],
 ['univ head var','_ =.. [_,a]','instantiation_error'],
 ['univ head nonatom tail','_ =.. [1,a]','type_error(atom)'],
 ['univ singleton compound','_ =.. [f(a)]','type_error(atomic)'],
 ['univ empty','_ =.. []','domain_error(non_empty_list)'],
 ['is var expr','_ is _','instantiation_error'],
 ['arith comp var left','_ =:= 1','instantiation_error'],
 ['arith comp var right','1 =:= _','instantiation_error'],
 ['clause head var','clause(_,_)','instantiation_error'],
 ['clause head noncallable','clause(1,_)','type_error(callable)'],
 ['clause body noncallable','clause(p,1)','type_error(callable)'],
 ['current_predicate bad','current_predicate(foo)','type_error(predicate_indicator)'],
 ['asserta head var','asserta(_)','instantiation_error'],
 ['asserta noncallable','asserta(1)','type_error(callable)'],
 ['asserta bad body','asserta((p:-1))','type_error(callable)'],
 ['retract head var','retract(_)','instantiation_error'],
 ['retract noncallable','retract(1)','type_error(callable)'],
 ['abolish var','abolish(_)','instantiation_error'],
 ['abolish partial PI','abolish(_/1)','instantiation_error'],
 ['abolish bad PI','abolish(foo)','type_error(predicate_indicator)'],
 ['abolish arity type','abolish(a/a)','type_error(integer)'],
 ['abolish name type','abolish(1/1)','type_error(atom)'],
 ['abolish negative','abolish(a/ -1)','domain_error(not_less_than_zero)'],
 ['findall goal var','findall(_,_,[])','instantiation_error'],
 ['findall goal noncallable','findall(_,1,[])','type_error(callable)'],
 ['findall instances nonlist','findall(_,true,foo)','type_error(list)'],
 ['bagof goal var','bagof(_,_,[])','instantiation_error'],
 ['bagof goal noncallable','bagof(_,1,[])','type_error(callable)'],
 ['bagof instances nonlist','bagof(_,true,foo)','type_error(list)'],
 ['setof goal var','setof(_,_,[])','instantiation_error'],
 ['setof goal noncallable','setof(_,1,[])','type_error(callable)'],
 ['setof instances nonlist','setof(_,true,foo)','type_error(list)'],
 ['neg var','\\+ _','instantiation_error'],
 ['neg noncallable','\\+ 1','type_error(callable)'],
 ['once var','once(_)','instantiation_error'],
 ['once noncallable','once(1)','type_error(callable)'],
 ['atom_length var atom','atom_length(_,_)','instantiation_error'],
 ['atom_length atom type','atom_length(1,_)','type_error(atom)'],
 ['atom_length len type','atom_length(a,a)','type_error(integer)'],
 ['atom_length len neg','atom_length(a,-1)','domain_error(not_less_than_zero)'],
 ['atom_concat both unknown 1','atom_concat(_,a,_)','instantiation_error'],
 ['atom_concat both unknown 2','atom_concat(a,_,_)','instantiation_error'],
 ['atom_concat a1 type','atom_concat(1,a,_)','type_error(atom)'],
 ['atom_concat a2 type','atom_concat(a,1,_)','type_error(atom)'],
 ['atom_concat a12 type','atom_concat(a,a,1)','type_error(atom)'],
 ['sub_atom atom var','sub_atom(_,_,_,_,_)','instantiation_error'],
 ['sub_atom atom type','sub_atom(1,_,_,_,_)','type_error(atom)'],
 ['sub_atom sub type','sub_atom(a,_,_,_,1)','type_error(atom)'],
 ['sub_atom before type','sub_atom(a,a,_,_,_)','type_error(integer)'],
 ['sub_atom length type','sub_atom(a,_,a,_,_)','type_error(integer)'],
 ['sub_atom after type','sub_atom(a,_,_,a,_)','type_error(integer)'],
 ['sub_atom before neg','sub_atom(a,-1,_,_,_)','domain_error(not_less_than_zero)'],
 ['sub_atom length neg','sub_atom(a,_,-1,_,_)','domain_error(not_less_than_zero)'],
 ['sub_atom after neg','sub_atom(a,_,_,-1,_)','domain_error(not_less_than_zero)'],
 ['atom_chars partial','atom_chars(_,[_|_])','instantiation_error'],
 ['atom_chars atom type','atom_chars(1,_)','type_error(atom)'],
 ['atom_chars list type','atom_chars(_,foo)','type_error(list)'],
 ['atom_chars elem type','atom_chars(_,[1])','type_error(character)'],
 ['atom_codes partial','atom_codes(_,[_|_])','instantiation_error'],
 ['atom_codes atom type','atom_codes(1,_)','type_error(atom)'],
 ['atom_codes list type','atom_codes(_,foo)','type_error(list)'],
 ['atom_codes elem repr','atom_codes(_,[999])','representation_error(character_code)'],
 ['char_code both var','char_code(_,_)','instantiation_error'],
 ['char_code char type','char_code(ab,_)','type_error(character)'],
 ['char_code code type','char_code(a,a)','type_error(integer)'],
 ['char_code code repr','char_code(_,999)','representation_error(character_code)'],
 ['number_chars partial','number_chars(_,[_|_])','instantiation_error'],
 ['number_chars num type','number_chars(1+1,_)','type_error(number)'],
 ['number_chars list type','number_chars(_,foo)','type_error(list)'],
 ['number_chars elem type','number_chars(_,[1])','type_error(character)'],
 ['number_chars syntax','number_chars(_,[a])','syntax_error'],
 ['number_codes partial','number_codes(_,[_|_])','instantiation_error'],
 ['number_codes num type','number_codes(1+1,_)','type_error(number)'],
 ['number_codes list type','number_codes(_,foo)','type_error(list)'],
 ['number_codes elem repr','number_codes(_,[999])','representation_error(character_code)'],
 ['number_codes syntax','number_codes(_,[97])','syntax_error'],
 ['halt var','halt(_)','instantiation_error'],
 ['halt type','halt(a)','type_error(integer)'],
];
function formal(goal){try{run('',{isoStrict:true,goal}); return 'SUCCESS/FAIL';}catch(e){return e.formal??e.message}}
let bad=0;
for(const [label,goal,expected] of cases){const got=formal(goal); const ok=got===expected || (expected==='syntax_error' && got?.startsWith('syntax_error')); if(!ok) bad++; console.log(`${ok?'OK':'BAD'}\t${label}\t${goal}\texp=${expected}\tgot=${got}`)}
console.log('mismatches',bad,'of',cases.length);
