import fs from 'node:fs';
import { run } from './src/index.js';
fs.writeFileSync('iso-probe-text.txt','ab');
fs.writeFileSync('iso-probe-bin.dat',Buffer.from([65,66]));
const cases = [
 ['current_input bad','current_input(foo)','domain_error(stream)'],
 ['current_output bad','current_output(foo)','domain_error(stream)'],
 ['set_input var','set_input(_)','instantiation_error'],
 ['set_input domain','set_input(1)','domain_error(stream_or_alias)'],
 ['set_input missing','set_input(no_such_alias)','existence_error(stream)'],
 ['set_input output','set_input(user_output)','permission_error(input, stream)'],
 ['set_output var','set_output(_)','instantiation_error'],
 ['set_output domain','set_output(1)','domain_error(stream_or_alias)'],
 ['set_output missing','set_output(no_such_alias)','existence_error(stream)'],
 ['set_output input','set_output(user_input)','permission_error(output, stream)'],
 ['open source var','open(_,read,S,[])','instantiation_error'],
 ['open mode var','open(iso_probe_text,_,S,[])','instantiation_error'],
 ['open opts var elem','open(iso_probe_text,read,S,[X])','instantiation_error'],
 ['open opts component var','open(iso_probe_text,read,S,[type(X)])','instantiation_error'],
 ['open mode type','open(iso_probe_text,1,S,[])','type_error(atom)'],
 ['open opts nonlist','open(iso_probe_text,read,S,foo)','type_error(list)'],
 ['open stream nonvar','open(iso_probe_text,read,x,[])','uninstantiation_error'],
 ['open source domain','open(1,read,S,[])','domain_error(source_sink)'],
 ['open mode domain','open(iso_probe_text,bad,S,[])','domain_error(io_mode)'],
 ['open option domain','open(iso_probe_text,read,S,[bogus])','domain_error(stream_option)'],
 ['open type option domain','open(iso_probe_text,read,S,[type(1)])','domain_error(stream_option)'],
 ['open alias option domain','open(iso_probe_text,read,S,[alias(1)])','domain_error(stream_option)'],
 ['open missing','open(no_such_file_zz,read,S,[])','existence_error(source_sink)'],
 ['close stream var','close(_,[])','instantiation_error'],
 ['close opts partial','close(user_output,[force(true)|_])','instantiation_error'],
 ['close opts component var','close(user_output,[force(X)])','instantiation_error'],
 ['close opts nonlist','close(user_output,foo)','type_error(list)'],
 ['close stream domain','close(1,[])','domain_error(stream_or_alias)'],
 ['close invalid option','close(user_output,[bogus])','domain_error(close_option)'],
 ['close missing','close(no_such_alias,[])','existence_error(stream)'],
 ['flush var','flush_output(_)','instantiation_error'],
 ['flush domain','flush_output(1)','domain_error(stream_or_alias)'],
 ['flush missing','flush_output(no_such_alias)','existence_error(stream)'],
 ['flush input','flush_output(user_input)','permission_error(output, stream)'],
 ['stream_property stream bad','stream_property(1,_)','domain_error(stream)'],
 ['stream_property property bad','stream_property(_,bogus)','domain_error(stream_property)'],
 ['at_end var','at_end_of_stream(_)','instantiation_error'],
 ['at_end domain','at_end_of_stream(1)','domain_error(stream_or_alias)'],
 ['at_end missing','at_end_of_stream(no_such_alias)','existence_error(stream)'],
 ['setpos stream var first','set_stream_position(_,_)','instantiation_error'],
 ['setpos pos var second','set_stream_position(1,_)','instantiation_error'],
 ['setpos stream domain','set_stream_position(1,0)','domain_error(stream_or_alias)'],
 ['setpos pos domain before existence','set_stream_position(no_such_alias,foo)','domain_error(stream_position)'],
 ['setpos missing','set_stream_position(no_such_alias,0)','existence_error(stream)'],
 // character input target validation / stream precedence
 ['get_char stream var','get_char(_,ab)','instantiation_error'],
 ['get_char target type','get_char(1,ab)','type_error(in_character)'],
 ['get_char stream domain after target','get_char(1,a)','domain_error(stream_or_alias)'],
 ['get_code target type','get_code(1,a)','type_error(integer)'],
 ['get_code target repr','get_code(user_input,999)','representation_error(in_character_code)'],
 ['peek_char target type','peek_char(1,ab)','type_error(in_character)'],
 ['peek_code target type','peek_code(1,a)','type_error(integer)'],
 ['put_char stream var','put_char(_,a)','instantiation_error'],
 ['put_char char var','put_char(user_output,_)','instantiation_error'],
 ['put_char char type before stream','put_char(1,ab)','type_error(character)'],
 ['put_char stream domain','put_char(1,a)','domain_error(stream_or_alias)'],
 ['put_code code var','put_code(user_output,_)','instantiation_error'],
 ['put_code code type before stream','put_code(1,a)','type_error(integer)'],
 ['put_code stream domain','put_code(1,65)','domain_error(stream_or_alias)'],
 ['put_code repr','put_code(user_output,999)','representation_error(character_code)'],
 ['get_byte target type','get_byte(1,999)','type_error(in_byte)'],
 ['peek_byte target type','peek_byte(1,999)','type_error(in_byte)'],
 ['put_byte stream var','put_byte(_,1)','instantiation_error'],
 ['put_byte byte var','put_byte(user_output,_)','instantiation_error'],
 ['put_byte byte type before stream','put_byte(1,999)','type_error(byte)'],
 ['put_byte stream domain','put_byte(1,1)','domain_error(stream_or_alias)'],
];
function formal(goal){try{run('',{isoStrict:true,goal}); return 'SUCCESS/FAIL';}catch(e){return e.formal??e.message}}
let bad=0;
for(const [label,goal,expected] of cases){const got=formal(goal);const ok=got===expected;if(!ok)bad++;console.log(`${ok?'OK':'BAD'}\t${label}\t${goal}\texp=${expected}\tgot=${got}`)}
console.log('mismatches',bad,'of',cases.length);
fs.rmSync('iso-probe-text.txt',{force:true});fs.rmSync('iso-probe-bin.dat',{force:true});
