optimalTour([aaa, bbb, ccc, ddd, eee, fff, ggg], [[aaa, bbb, fff, ccc, eee, ddd, ggg], 75]).
why(
  optimalTour([aaa, bbb, ccc, ddd, eee, fff, ggg], [[aaa, bbb, fff, ccc, eee, ddd, ggg], 75]),
  proof(
    goal(optimalTour([aaa, bbb, ccc, ddd, eee, fff, ggg], [[aaa, bbb, fff, ccc, eee, ddd, ggg], 75])), by(rule("traveling-salesman.pl", clause(26))),
    bindings([binding("Cities", [aaa, bbb, ccc, ddd, eee, fff, ggg]), binding("Optimal", [[aaa, bbb, fff, ccc, eee, ddd, ggg], 75]), binding("Solutions", [[[aaa, bbb, ccc, eee, fff, ddd, ggg], 120], [[aaa, bbb, ccc, fff, eee, ddd, ggg], 90], [[aaa, bbb, eee, ccc, fff, ddd, ggg], 95], [[aaa, bbb, eee, fff, ccc, ddd, ggg], 95], [[aaa, bbb, fff, eee, ccc, ddd, ggg], 105], [[aaa, bbb, fff, ccc, eee, ddd, ggg], 75], [[aaa, ccc, bbb, eee, fff, ddd, ggg], 130], [[aaa, ccc, bbb, fff, eee, ddd, ggg], 110], [[aaa, ccc, eee, bbb, fff, ddd, ggg], 115], [[aaa, ccc, eee, fff, bbb, ddd, ggg], 120], [[aaa, ccc, fff, eee, bbb, ddd, ggg], 110], [[aaa, ccc, fff, bbb, eee, ddd, ggg], 85], [[aaa, eee, ccc, bbb, fff, ddd, ggg], 140], [[aaa, eee, ccc, fff, bbb, ddd, ggg], 120], [[aaa, eee, bbb, ccc, fff, ddd, ggg], 130], [[aaa, eee, bbb, fff, ccc, ddd, ggg], 115], [[aaa, eee, fff, bbb, ccc, ddd, ggg], 140], [[aaa, eee, fff, ccc, bbb, ddd, ggg], 135], [[aaa, fff, ccc, eee, bbb, ddd, ggg], 120], [[aaa, fff, ccc, bbb, eee, ddd, ggg], 110], [[aaa, fff, eee, ccc, bbb, ddd, ggg], 145], [[aaa, fff, eee, bbb, ccc, ddd, ggg], 140], [[aaa, fff, bbb, eee, ccc, ddd, ggg], 125], [[aaa, fff, bbb, ccc, eee, ddd, ggg], 120]])]),
    uses([
      proof(goal(target_cities([aaa, bbb, ccc, ddd, eee, fff, ggg])), by(fact("traveling-salesman.pl", clause(2)))),
      proof(goal(findall([T, D], tsp([aaa, bbb, ccc, ddd, eee, fff, ggg], T, D), [[[aaa, bbb, ccc, eee, fff, ddd, ggg], 120], [[aaa, bbb, ccc, fff, eee, ddd, ggg], 90], [[aaa, bbb, eee, ccc, fff, ddd, ggg], 95], [[aaa, bbb, eee, fff, ccc, ddd, ggg], 95], [[aaa, bbb, fff, eee, ccc, ddd, ggg], 105], [[aaa, bbb, fff, ccc, eee, ddd, ggg], 75], [[aaa, ccc, bbb, eee, fff, ddd, ggg], 130], [[aaa, ccc, bbb, fff, eee, ddd, ggg], 110], [[aaa, ccc, eee, bbb, fff, ddd, ggg], 115], [[aaa, ccc, eee, fff, bbb, ddd, ggg], 120], [[aaa, ccc, fff, eee, bbb, ddd, ggg], 110], [[aaa, ccc, fff, bbb, eee, ddd, ggg], 85], [[aaa, eee, ccc, bbb, fff, ddd, ggg], 140], [[aaa, eee, ccc, fff, bbb, ddd, ggg], 120], [[aaa, eee, bbb, ccc, fff, ddd, ggg], 130], [[aaa, eee, bbb, fff, ccc, ddd, ggg], 115], [[aaa, eee, fff, bbb, ccc, ddd, ggg], 140], [[aaa, eee, fff, ccc, bbb, ddd, ggg], 135], [[aaa, fff, ccc, eee, bbb, ddd, ggg], 120], [[aaa, fff, ccc, bbb, eee, ddd, ggg], 110], [[aaa, fff, eee, ccc, bbb, ddd, ggg], 145], [[aaa, fff, eee, bbb, ccc, ddd, ggg], 140], [[aaa, fff, bbb, eee, ccc, ddd, ggg], 125], [[aaa, fff, bbb, ccc, eee, ddd, ggg], 120]])), by(builtin(findall, 3))),
      proof(
        goal(min_distance([[[aaa, bbb, ccc, eee, fff, ddd, ggg], 120], [[aaa, bbb, ccc, fff, eee, ddd, ggg], 90], [[aaa, bbb, eee, ccc, fff, ddd, ggg], 95], [[aaa, bbb, eee, fff, ccc, ddd, ggg], 95], [[aaa, bbb, fff, eee, ccc, ddd, ggg], 105], [[aaa, bbb, fff, ccc, eee, ddd, ggg], 75], [[aaa, ccc, bbb, eee, fff, ddd, ggg], 130], [[aaa, ccc, bbb, fff, eee, ddd, ggg], 110], [[aaa, ccc, eee, bbb, fff, ddd, ggg], 115], [[aaa, ccc, eee, fff, bbb, ddd, ggg], 120], [[aaa, ccc, fff, eee, bbb, ddd, ggg], 110], [[aaa, ccc, fff, bbb, eee, ddd, ggg], 85], [[aaa, eee, ccc, bbb, fff, ddd, ggg], 140], [[aaa, eee, ccc, fff, bbb, ddd, ggg], 120], [[aaa, eee, bbb, ccc, fff, ddd, ggg], 130], [[aaa, eee, bbb, fff, ccc, ddd, ggg], 115], [[aaa, eee, fff, bbb, ccc, ddd, ggg], 140], [[aaa, eee, fff, ccc, bbb, ddd, ggg], 135], [[aaa, fff, ccc, eee, bbb, ddd, ggg], 120], [[aaa, fff, ccc, bbb, eee, ddd, ggg], 110], [[aaa, fff, eee, ccc, bbb, ddd, ggg], 145], [[aaa, fff, eee, bbb, ccc, ddd, ggg], 140], [[aaa, fff, bbb, eee, ccc, ddd, ggg], 125], [[aaa, fff, bbb, ccc, eee, ddd, ggg], 120]], [[aaa, bbb, fff, ccc, eee, ddd, ggg], 75])), by(rule("traveling-salesman.pl", clause(27))),
        bindings([binding("Sol", [[aaa, bbb, ccc, eee, fff, ddd, ggg], 120]), binding("Sols", [[[aaa, bbb, ccc, fff, eee, ddd, ggg], 90], [[aaa, bbb, eee, ccc, fff, ddd, ggg], 95], [[aaa, bbb, eee, fff, ccc, ddd, ggg], 95], [[aaa, bbb, fff, eee, ccc, ddd, ggg], 105], [[aaa, bbb, fff, ccc, eee, ddd, ggg], 75], [[aaa, ccc, bbb, eee, fff, ddd, ggg], 130], [[aaa, ccc, bbb, fff, eee, ddd, ggg], 110], [[aaa, ccc, eee, bbb, fff, ddd, ggg], 115], [[aaa, ccc, eee, fff, bbb, ddd, ggg], 120], [[aaa, ccc, fff, eee, bbb, ddd, ggg], 110], [[aaa, ccc, fff, bbb, eee, ddd, ggg], 85], [[aaa, eee, ccc, bbb, fff, ddd, ggg], 140], [[aaa, eee, ccc, fff, bbb, ddd, ggg], 120], [[aaa, eee, bbb, ccc, fff, ddd, ggg], 130], [[aaa, eee, bbb, fff, ccc, ddd, ggg], 115], [[aaa, eee, fff, bbb, ccc, ddd, ggg], 140], [[aaa, eee, fff, ccc, bbb, ddd, ggg], 135], [[aaa, fff, ccc, eee, bbb, ddd, ggg], 120], [[aaa, fff, ccc, bbb, eee, ddd, ggg], 110], [[aaa, fff, eee, ccc, bbb, ddd, ggg], 145], [[aaa, fff, eee, bbb, ccc, ddd, ggg], 140], [[aaa, fff, bbb, eee, ccc, ddd, ggg], 125], [[aaa, fff, bbb, ccc, eee, ddd, ggg], 120]]), binding("Optimal", [[aaa, bbb, fff, ccc, eee, ddd, ggg], 75])]),
        uses([
          proof(
            goal(min_distance_acc([[[aaa, bbb, ccc, fff, eee, ddd, ggg], 90], [[aaa, bbb, eee, ccc, fff, ddd, ggg], 95], [[aaa, bbb, eee, fff, ccc, ddd, ggg], 95], [[aaa, bbb, fff, eee, ccc, ddd, ggg], 105], [[aaa, bbb, fff, ccc, eee, ddd, ggg], 75], [[aaa, ccc, bbb, eee, fff, ddd, ggg], 130], [[aaa, ccc, bbb, fff, eee, ddd, ggg], 110], [[aaa, ccc, eee, bbb, fff, ddd, ggg], 115], [[aaa, ccc, eee, fff, bbb, ddd, ggg], 120], [[aaa, ccc, fff, eee, bbb, ddd, ggg], 110], [[aaa, ccc, fff, bbb, eee, ddd, ggg], 85], [[aaa, eee, ccc, bbb, fff, ddd, ggg], 140], [[aaa, eee, ccc, fff, bbb, ddd, ggg], 120], [[aaa, eee, bbb, ccc, fff, ddd, ggg], 130], [[aaa, eee, bbb, fff, ccc, ddd, ggg], 115], [[aaa, eee, fff, bbb, ccc, ddd, ggg], 140], [[aaa, eee, fff, ccc, bbb, ddd, ggg], 135], [[aaa, fff, ccc, eee, bbb, ddd, ggg], 120], [[aaa, fff, ccc, bbb, eee, ddd, ggg], 110], [[aaa, fff, eee, ccc, bbb, ddd, ggg], 145], [[aaa, fff, eee, bbb, ccc, ddd, ggg], 140], [[aaa, fff, bbb, eee, ccc, ddd, ggg], 125], [[aaa, fff, bbb, ccc, eee, ddd, ggg], 120]], [[aaa, bbb, ccc, eee, fff, ddd, ggg], 120], [[aaa, bbb, fff, ccc, eee, ddd, ggg], 75])), by(rule("traveling-salesman.pl", clause(29))),
            bindings([binding("_T", [aaa, bbb, ccc, fff, eee, ddd, ggg]), binding("D", 90), binding("Rest", [[[aaa, bbb, eee, ccc, fff, ddd, ggg], 95], [[aaa, bbb, eee, fff, ccc, ddd, ggg], 95], [[aaa, bbb, fff, eee, ccc, ddd, ggg], 105], [[aaa, bbb, fff, ccc, eee, ddd, ggg], 75], [[aaa, ccc, bbb, eee, fff, ddd, ggg], 130], [[aaa, ccc, bbb, fff, eee, ddd, ggg], 110], [[aaa, ccc, eee, bbb, fff, ddd, ggg], 115], [[aaa, ccc, eee, fff, bbb, ddd, ggg], 120], [[aaa, ccc, fff, eee, bbb, ddd, ggg], 110], [[aaa, ccc, fff, bbb, eee, ddd, ggg], 85], [[aaa, eee, ccc, bbb, fff, ddd, ggg], 140], [[aaa, eee, ccc, fff, bbb, ddd, ggg], 120], [[aaa, eee, bbb, ccc, fff, ddd, ggg], 130], [[aaa, eee, bbb, fff, ccc, ddd, ggg], 115], [[aaa, eee, fff, bbb, ccc, ddd, ggg], 140], [[aaa, eee, fff, ccc, bbb, ddd, ggg], 135], [[aaa, fff, ccc, eee, bbb, ddd, ggg], 120], [[aaa, fff, ccc, bbb, eee, ddd, ggg], 110], [[aaa, fff, eee, ccc, bbb, ddd, ggg], 145], [[aaa, fff, eee, bbb, ccc, ddd, ggg], 140], [[aaa, fff, bbb, eee, ccc, ddd, ggg], 125], [[aaa, fff, bbb, ccc, eee, ddd, ggg], 120]]), binding("_BestTour", [aaa, bbb, ccc, eee, fff, ddd, ggg]), binding("BestDistance", 120), binding("Optimal", [[aaa, bbb, fff, ccc, eee, ddd, ggg], 75])]),
            uses([
              proof(goal(lt(90, 120)), by(builtin(lt, 2))),
              proof(
                goal(min_distance_acc([[[aaa, bbb, eee, ccc, fff, ddd, ggg], 95], [[aaa, bbb, eee, fff, ccc, ddd, ggg], 95], [[aaa, bbb, fff, eee, ccc, ddd, ggg], 105], [[aaa, bbb, fff, ccc, eee, ddd, ggg], 75], [[aaa, ccc, bbb, eee, fff, ddd, ggg], 130], [[aaa, ccc, bbb, fff, eee, ddd, ggg], 110], [[aaa, ccc, eee, bbb, fff, ddd, ggg], 115], [[aaa, ccc, eee, fff, bbb, ddd, ggg], 120], [[aaa, ccc, fff, eee, bbb, ddd, ggg], 110], [[aaa, ccc, fff, bbb, eee, ddd, ggg], 85], [[aaa, eee, ccc, bbb, fff, ddd, ggg], 140], [[aaa, eee, ccc, fff, bbb, ddd, ggg], 120], [[aaa, eee, bbb, ccc, fff, ddd, ggg], 130], [[aaa, eee, bbb, fff, ccc, ddd, ggg], 115], [[aaa, eee, fff, bbb, ccc, ddd, ggg], 140], [[aaa, eee, fff, ccc, bbb, ddd, ggg], 135], [[aaa, fff, ccc, eee, bbb, ddd, ggg], 120], [[aaa, fff, ccc, bbb, eee, ddd, ggg], 110], [[aaa, fff, eee, ccc, bbb, ddd, ggg], 145], [[aaa, fff, eee, bbb, ccc, ddd, ggg], 140], [[aaa, fff, bbb, eee, ccc, ddd, ggg], 125], [[aaa, fff, bbb, ccc, eee, ddd, ggg], 120]], [[aaa, bbb, ccc, fff, eee, ddd, ggg], 90], [[aaa, bbb, fff, ccc, eee, ddd, ggg], 75])), by(rule("traveling-salesman.pl", clause(30))),
                bindings([binding("_T", [aaa, bbb, eee, ccc, fff, ddd, ggg]), binding("D", 95), binding("Rest", [[[aaa, bbb, eee, fff, ccc, ddd, ggg], 95], [[aaa, bbb, fff, eee, ccc, ddd, ggg], 105], [[aaa, bbb, fff, ccc, eee, ddd, ggg], 75], [[aaa, ccc, bbb, eee, fff, ddd, ggg], 130], [[aaa, ccc, bbb, fff, eee, ddd, ggg], 110], [[aaa, ccc, eee, bbb, fff, ddd, ggg], 115], [[aaa, ccc, eee, fff, bbb, ddd, ggg], 120], [[aaa, ccc, fff, eee, bbb, ddd, ggg], 110], [[aaa, ccc, fff, bbb, eee, ddd, ggg], 85], [[aaa, eee, ccc, bbb, fff, ddd, ggg], 140], [[aaa, eee, ccc, fff, bbb, ddd, ggg], 120], [[aaa, eee, bbb, ccc, fff, ddd, ggg], 130], [[aaa, eee, bbb, fff, ccc, ddd, ggg], 115], [[aaa, eee, fff, bbb, ccc, ddd, ggg], 140], [[aaa, eee, fff, ccc, bbb, ddd, ggg], 135], [[aaa, fff, ccc, eee, bbb, ddd, ggg], 120], [[aaa, fff, ccc, bbb, eee, ddd, ggg], 110], [[aaa, fff, eee, ccc, bbb, ddd, ggg], 145], [[aaa, fff, eee, bbb, ccc, ddd, ggg], 140], [[aaa, fff, bbb, eee, ccc, ddd, ggg], 125], [[aaa, fff, bbb, ccc, eee, ddd, ggg], 120]]), binding("BestTour", [aaa, bbb, ccc, fff, eee, ddd, ggg]), binding("BestDistance", 90), binding("Optimal", [[aaa, bbb, fff, ccc, eee, ddd, ggg], 75])]),
                uses([
                  proof(goal(ge(95, 90)), by(builtin(ge, 2))),
                  proof(
                    goal(min_distance_acc([[[aaa, bbb, eee, fff, ccc, ddd, ggg], 95], [[aaa, bbb, fff, eee, ccc, ddd, ggg], 105], [[aaa, bbb, fff, ccc, eee, ddd, ggg], 75], [[aaa, ccc, bbb, eee, fff, ddd, ggg], 130], [[aaa, ccc, bbb, fff, eee, ddd, ggg], 110], [[aaa, ccc, eee, bbb, fff, ddd, ggg], 115], [[aaa, ccc, eee, fff, bbb, ddd, ggg], 120], [[aaa, ccc, fff, eee, bbb, ddd, ggg], 110], [[aaa, ccc, fff, bbb, eee, ddd, ggg], 85], [[aaa, eee, ccc, bbb, fff, ddd, ggg], 140], [[aaa, eee, ccc, fff, bbb, ddd, ggg], 120], [[aaa, eee, bbb, ccc, fff, ddd, ggg], 130], [[aaa, eee, bbb, fff, ccc, ddd, ggg], 115], [[aaa, eee, fff, bbb, ccc, ddd, ggg], 140], [[aaa, eee, fff, ccc, bbb, ddd, ggg], 135], [[aaa, fff, ccc, eee, bbb, ddd, ggg], 120], [[aaa, fff, ccc, bbb, eee, ddd, ggg], 110], [[aaa, fff, eee, ccc, bbb, ddd, ggg], 145], [[aaa, fff, eee, bbb, ccc, ddd, ggg], 140], [[aaa, fff, bbb, eee, ccc, ddd, ggg], 125], [[aaa, fff, bbb, ccc, eee, ddd, ggg], 120]], [[aaa, bbb, ccc, fff, eee, ddd, ggg], 90], [[aaa, bbb, fff, ccc, eee, ddd, ggg], 75])), by(rule("traveling-salesman.pl", clause(30))),
                    bindings([binding("_T", [aaa, bbb, eee, fff, ccc, ddd, ggg]), binding("D", 95), binding("Rest", [[[aaa, bbb, fff, eee, ccc, ddd, ggg], 105], [[aaa, bbb, fff, ccc, eee, ddd, ggg], 75], [[aaa, ccc, bbb, eee, fff, ddd, ggg], 130], [[aaa, ccc, bbb, fff, eee, ddd, ggg], 110], [[aaa, ccc, eee, bbb, fff, ddd, ggg], 115], [[aaa, ccc, eee, fff, bbb, ddd, ggg], 120], [[aaa, ccc, fff, eee, bbb, ddd, ggg], 110], [[aaa, ccc, fff, bbb, eee, ddd, ggg], 85], [[aaa, eee, ccc, bbb, fff, ddd, ggg], 140], [[aaa, eee, ccc, fff, bbb, ddd, ggg], 120], [[aaa, eee, bbb, ccc, fff, ddd, ggg], 130], [[aaa, eee, bbb, fff, ccc, ddd, ggg], 115], [[aaa, eee, fff, bbb, ccc, ddd, ggg], 140], [[aaa, eee, fff, ccc, bbb, ddd, ggg], 135], [[aaa, fff, ccc, eee, bbb, ddd, ggg], 120], [[aaa, fff, ccc, bbb, eee, ddd, ggg], 110], [[aaa, fff, eee, ccc, bbb, ddd, ggg], 145], [[aaa, fff, eee, bbb, ccc, ddd, ggg], 140], [[aaa, fff, bbb, eee, ccc, ddd, ggg], 125], [[aaa, fff, bbb, ccc, eee, ddd, ggg], 120]]), binding("BestTour", [aaa, bbb, ccc, fff, eee, ddd, ggg]), binding("BestDistance", 90), binding("Optimal", [[aaa, bbb, fff, ccc, eee, ddd, ggg], 75])]),
                    uses([
                      proof(goal(ge(95, 90)), by(builtin(ge, 2))),
                      proof(
                        goal(min_distance_acc([[[aaa, bbb, fff, eee, ccc, ddd, ggg], 105], [[aaa, bbb, fff, ccc, eee, ddd, ggg], 75], [[aaa, ccc, bbb, eee, fff, ddd, ggg], 130], [[aaa, ccc, bbb, fff, eee, ddd, ggg], 110], [[aaa, ccc, eee, bbb, fff, ddd, ggg], 115], [[aaa, ccc, eee, fff, bbb, ddd, ggg], 120], [[aaa, ccc, fff, eee, bbb, ddd, ggg], 110], [[aaa, ccc, fff, bbb, eee, ddd, ggg], 85], [[aaa, eee, ccc, bbb, fff, ddd, ggg], 140], [[aaa, eee, ccc, fff, bbb, ddd, ggg], 120], [[aaa, eee, bbb, ccc, fff, ddd, ggg], 130], [[aaa, eee, bbb, fff, ccc, ddd, ggg], 115], [[aaa, eee, fff, bbb, ccc, ddd, ggg], 140], [[aaa, eee, fff, ccc, bbb, ddd, ggg], 135], [[aaa, fff, ccc, eee, bbb, ddd, ggg], 120], [[aaa, fff, ccc, bbb, eee, ddd, ggg], 110], [[aaa, fff, eee, ccc, bbb, ddd, ggg], 145], [[aaa, fff, eee, bbb, ccc, ddd, ggg], 140], [[aaa, fff, bbb, eee, ccc, ddd, ggg], 125], [[aaa, fff, bbb, ccc, eee, ddd, ggg], 120]], [[aaa, bbb, ccc, fff, eee, ddd, ggg], 90], [[aaa, bbb, fff, ccc, eee, ddd, ggg], 75])), by(rule("traveling-salesman.pl", clause(30))),
                        bindings([binding("_T", [aaa, bbb, fff, eee, ccc, ddd, ggg]), binding("D", 105), binding("Rest", [[[aaa, bbb, fff, ccc, eee, ddd, ggg], 75], [[aaa, ccc, bbb, eee, fff, ddd, ggg], 130], [[aaa, ccc, bbb, fff, eee, ddd, ggg], 110], [[aaa, ccc, eee, bbb, fff, ddd, ggg], 115], [[aaa, ccc, eee, fff, bbb, ddd, ggg], 120], [[aaa, ccc, fff, eee, bbb, ddd, ggg], 110], [[aaa, ccc, fff, bbb, eee, ddd, ggg], 85], [[aaa, eee, ccc, bbb, fff, ddd, ggg], 140], [[aaa, eee, ccc, fff, bbb, ddd, ggg], 120], [[aaa, eee, bbb, ccc, fff, ddd, ggg], 130], [[aaa, eee, bbb, fff, ccc, ddd, ggg], 115], [[aaa, eee, fff, bbb, ccc, ddd, ggg], 140], [[aaa, eee, fff, ccc, bbb, ddd, ggg], 135], [[aaa, fff, ccc, eee, bbb, ddd, ggg], 120], [[aaa, fff, ccc, bbb, eee, ddd, ggg], 110], [[aaa, fff, eee, ccc, bbb, ddd, ggg], 145], [[aaa, fff, eee, bbb, ccc, ddd, ggg], 140], [[aaa, fff, bbb, eee, ccc, ddd, ggg], 125], [[aaa, fff, bbb, ccc, eee, ddd, ggg], 120]]), binding("BestTour", [aaa, bbb, ccc, fff, eee, ddd, ggg]), binding("BestDistance", 90), binding("Optimal", [[aaa, bbb, fff, ccc, eee, ddd, ggg], 75])]),
                        uses([
                          proof(goal(ge(105, 90)), by(builtin(ge, 2))),
                          proof(
                            goal(min_distance_acc([[[aaa, bbb, fff, ccc, eee, ddd, ggg], 75], [[aaa, ccc, bbb, eee, fff, ddd, ggg], 130], [[aaa, ccc, bbb, fff, eee, ddd, ggg], 110], [[aaa, ccc, eee, bbb, fff, ddd, ggg], 115], [[aaa, ccc, eee, fff, bbb, ddd, ggg], 120], [[aaa, ccc, fff, eee, bbb, ddd, ggg], 110], [[aaa, ccc, fff, bbb, eee, ddd, ggg], 85], [[aaa, eee, ccc, bbb, fff, ddd, ggg], 140], [[aaa, eee, ccc, fff, bbb, ddd, ggg], 120], [[aaa, eee, bbb, ccc, fff, ddd, ggg], 130], [[aaa, eee, bbb, fff, ccc, ddd, ggg], 115], [[aaa, eee, fff, bbb, ccc, ddd, ggg], 140], [[aaa, eee, fff, ccc, bbb, ddd, ggg], 135], [[aaa, fff, ccc, eee, bbb, ddd, ggg], 120], [[aaa, fff, ccc, bbb, eee, ddd, ggg], 110], [[aaa, fff, eee, ccc, bbb, ddd, ggg], 145], [[aaa, fff, eee, bbb, ccc, ddd, ggg], 140], [[aaa, fff, bbb, eee, ccc, ddd, ggg], 125], [[aaa, fff, bbb, ccc, eee, ddd, ggg], 120]], [[aaa, bbb, ccc, fff, eee, ddd, ggg], 90], [[aaa, bbb, fff, ccc, eee, ddd, ggg], 75])), by(rule("traveling-salesman.pl", clause(29))),
                            bindings([binding("_T", [aaa, bbb, fff, ccc, eee, ddd, ggg]), binding("D", 75), binding("Rest", [[[aaa, ccc, bbb, eee, fff, ddd, ggg], 130], [[aaa, ccc, bbb, fff, eee, ddd, ggg], 110], [[aaa, ccc, eee, bbb, fff, ddd, ggg], 115], [[aaa, ccc, eee, fff, bbb, ddd, ggg], 120], [[aaa, ccc, fff, eee, bbb, ddd, ggg], 110], [[aaa, ccc, fff, bbb, eee, ddd, ggg], 85], [[aaa, eee, ccc, bbb, fff, ddd, ggg], 140], [[aaa, eee, ccc, fff, bbb, ddd, ggg], 120], [[aaa, eee, bbb, ccc, fff, ddd, ggg], 130], [[aaa, eee, bbb, fff, ccc, ddd, ggg], 115], [[aaa, eee, fff, bbb, ccc, ddd, ggg], 140], [[aaa, eee, fff, ccc, bbb, ddd, ggg], 135], [[aaa, fff, ccc, eee, bbb, ddd, ggg], 120], [[aaa, fff, ccc, bbb, eee, ddd, ggg], 110], [[aaa, fff, eee, ccc, bbb, ddd, ggg], 145], [[aaa, fff, eee, bbb, ccc, ddd, ggg], 140], [[aaa, fff, bbb, eee, ccc, ddd, ggg], 125], [[aaa, fff, bbb, ccc, eee, ddd, ggg], 120]]), binding("_BestTour", [aaa, bbb, ccc, fff, eee, ddd, ggg]), binding("BestDistance", 90), binding("Optimal", [[aaa, bbb, fff, ccc, eee, ddd, ggg], 75])]),
                            uses([
                              proof(goal(lt(75, 90)), by(builtin(lt, 2))),
                              proof(
                                goal(min_distance_acc([[[aaa, ccc, bbb, eee, fff, ddd, ggg], 130], [[aaa, ccc, bbb, fff, eee, ddd, ggg], 110], [[aaa, ccc, eee, bbb, fff, ddd, ggg], 115], [[aaa, ccc, eee, fff, bbb, ddd, ggg], 120], [[aaa, ccc, fff, eee, bbb, ddd, ggg], 110], [[aaa, ccc, fff, bbb, eee, ddd, ggg], 85], [[aaa, eee, ccc, bbb, fff, ddd, ggg], 140], [[aaa, eee, ccc, fff, bbb, ddd, ggg], 120], [[aaa, eee, bbb, ccc, fff, ddd, ggg], 130], [[aaa, eee, bbb, fff, ccc, ddd, ggg], 115], [[aaa, eee, fff, bbb, ccc, ddd, ggg], 140], [[aaa, eee, fff, ccc, bbb, ddd, ggg], 135], [[aaa, fff, ccc, eee, bbb, ddd, ggg], 120], [[aaa, fff, ccc, bbb, eee, ddd, ggg], 110], [[aaa, fff, eee, ccc, bbb, ddd, ggg], 145], [[aaa, fff, eee, bbb, ccc, ddd, ggg], 140], [[aaa, fff, bbb, eee, ccc, ddd, ggg], 125], [[aaa, fff, bbb, ccc, eee, ddd, ggg], 120]], [[aaa, bbb, fff, ccc, eee, ddd, ggg], 75], [[aaa, bbb, fff, ccc, eee, ddd, ggg], 75])), by(rule("traveling-salesman.pl", clause(30))),
                                bindings([binding("_T", [aaa, ccc, bbb, eee, fff, ddd, ggg]), binding("D", 130), binding("Rest", [[[aaa, ccc, bbb, fff, eee, ddd, ggg], 110], [[aaa, ccc, eee, bbb, fff, ddd, ggg], 115], [[aaa, ccc, eee, fff, bbb, ddd, ggg], 120], [[aaa, ccc, fff, eee, bbb, ddd, ggg], 110], [[aaa, ccc, fff, bbb, eee, ddd, ggg], 85], [[aaa, eee, ccc, bbb, fff, ddd, ggg], 140], [[aaa, eee, ccc, fff, bbb, ddd, ggg], 120], [[aaa, eee, bbb, ccc, fff, ddd, ggg], 130], [[aaa, eee, bbb, fff, ccc, ddd, ggg], 115], [[aaa, eee, fff, bbb, ccc, ddd, ggg], 140], [[aaa, eee, fff, ccc, bbb, ddd, ggg], 135], [[aaa, fff, ccc, eee, bbb, ddd, ggg], 120], [[aaa, fff, ccc, bbb, eee, ddd, ggg], 110], [[aaa, fff, eee, ccc, bbb, ddd, ggg], 145], [[aaa, fff, eee, bbb, ccc, ddd, ggg], 140], [[aaa, fff, bbb, eee, ccc, ddd, ggg], 125], [[aaa, fff, bbb, ccc, eee, ddd, ggg], 120]]), binding("BestTour", [aaa, bbb, fff, ccc, eee, ddd, ggg]), binding("BestDistance", 75), binding("Optimal", [[aaa, bbb, fff, ccc, eee, ddd, ggg], 75])]),
                                uses([
                                  proof(goal(ge(130, 75)), by(builtin(ge, 2))),
                                  proof(
                                    goal(min_distance_acc([[[aaa, ccc, bbb, fff, eee, ddd, ggg], 110], [[aaa, ccc, eee, bbb, fff, ddd, ggg], 115], [[aaa, ccc, eee, fff, bbb, ddd, ggg], 120], [[aaa, ccc, fff, eee, bbb, ddd, ggg], 110], [[aaa, ccc, fff, bbb, eee, ddd, ggg], 85], [[aaa, eee, ccc, bbb, fff, ddd, ggg], 140], [[aaa, eee, ccc, fff, bbb, ddd, ggg], 120], [[aaa, eee, bbb, ccc, fff, ddd, ggg], 130], [[aaa, eee, bbb, fff, ccc, ddd, ggg], 115], [[aaa, eee, fff, bbb, ccc, ddd, ggg], 140], [[aaa, eee, fff, ccc, bbb, ddd, ggg], 135], [[aaa, fff, ccc, eee, bbb, ddd, ggg], 120], [[aaa, fff, ccc, bbb, eee, ddd, ggg], 110], [[aaa, fff, eee, ccc, bbb, ddd, ggg], 145], [[aaa, fff, eee, bbb, ccc, ddd, ggg], 140], [[aaa, fff, bbb, eee, ccc, ddd, ggg], 125], [[aaa, fff, bbb, ccc, eee, ddd, ggg], 120]], [[aaa, bbb, fff, ccc, eee, ddd, ggg], 75], [[aaa, bbb, fff, ccc, eee, ddd, ggg], 75])), by(rule("traveling-salesman.pl", clause(30))),
                                    bindings([binding("_T", [aaa, ccc, bbb, fff, eee, ddd, ggg]), binding("D", 110), binding("Rest", [[[aaa, ccc, eee, bbb, fff, ddd, ggg], 115], [[aaa, ccc, eee, fff, bbb, ddd, ggg], 120], [[aaa, ccc, fff, eee, bbb, ddd, ggg], 110], [[aaa, ccc, fff, bbb, eee, ddd, ggg], 85], [[aaa, eee, ccc, bbb, fff, ddd, ggg], 140], [[aaa, eee, ccc, fff, bbb, ddd, ggg], 120], [[aaa, eee, bbb, ccc, fff, ddd, ggg], 130], [[aaa, eee, bbb, fff, ccc, ddd, ggg], 115], [[aaa, eee, fff, bbb, ccc, ddd, ggg], 140], [[aaa, eee, fff, ccc, bbb, ddd, ggg], 135], [[aaa, fff, ccc, eee, bbb, ddd, ggg], 120], [[aaa, fff, ccc, bbb, eee, ddd, ggg], 110], [[aaa, fff, eee, ccc, bbb, ddd, ggg], 145], [[aaa, fff, eee, bbb, ccc, ddd, ggg], 140], [[aaa, fff, bbb, eee, ccc, ddd, ggg], 125], [[aaa, fff, bbb, ccc, eee, ddd, ggg], 120]]), binding("BestTour", [aaa, bbb, fff, ccc, eee, ddd, ggg]), binding("BestDistance", 75), binding("Optimal", [[aaa, bbb, fff, ccc, eee, ddd, ggg], 75])]),
                                    uses([
                                      proof(goal(ge(110, 75)), by(builtin(ge, 2))),
                                      proof(
                                        goal(min_distance_acc([[[aaa, ccc, eee, bbb, fff, ddd, ggg], 115], [[aaa, ccc, eee, fff, bbb, ddd, ggg], 120], [[aaa, ccc, fff, eee, bbb, ddd, ggg], 110], [[aaa, ccc, fff, bbb, eee, ddd, ggg], 85], [[aaa, eee, ccc, bbb, fff, ddd, ggg], 140], [[aaa, eee, ccc, fff, bbb, ddd, ggg], 120], [[aaa, eee, bbb, ccc, fff, ddd, ggg], 130], [[aaa, eee, bbb, fff, ccc, ddd, ggg], 115], [[aaa, eee, fff, bbb, ccc, ddd, ggg], 140], [[aaa, eee, fff, ccc, bbb, ddd, ggg], 135], [[aaa, fff, ccc, eee, bbb, ddd, ggg], 120], [[aaa, fff, ccc, bbb, eee, ddd, ggg], 110], [[aaa, fff, eee, ccc, bbb, ddd, ggg], 145], [[aaa, fff, eee, bbb, ccc, ddd, ggg], 140], [[aaa, fff, bbb, eee, ccc, ddd, ggg], 125], [[aaa, fff, bbb, ccc, eee, ddd, ggg], 120]], [[aaa, bbb, fff, ccc, eee, ddd, ggg], 75], [[aaa, bbb, fff, ccc, eee, ddd, ggg], 75])), by(rule("traveling-salesman.pl", clause(30))),
                                        bindings([binding("_T", [aaa, ccc, eee, bbb, fff, ddd, ggg]), binding("D", 115), binding("Rest", [[[aaa, ccc, eee, fff, bbb, ddd, ggg], 120], [[aaa, ccc, fff, eee, bbb, ddd, ggg], 110], [[aaa, ccc, fff, bbb, eee, ddd, ggg], 85], [[aaa, eee, ccc, bbb, fff, ddd, ggg], 140], [[aaa, eee, ccc, fff, bbb, ddd, ggg], 120], [[aaa, eee, bbb, ccc, fff, ddd, ggg], 130], [[aaa, eee, bbb, fff, ccc, ddd, ggg], 115], [[aaa, eee, fff, bbb, ccc, ddd, ggg], 140], [[aaa, eee, fff, ccc, bbb, ddd, ggg], 135], [[aaa, fff, ccc, eee, bbb, ddd, ggg], 120], [[aaa, fff, ccc, bbb, eee, ddd, ggg], 110], [[aaa, fff, eee, ccc, bbb, ddd, ggg], 145], [[aaa, fff, eee, bbb, ccc, ddd, ggg], 140], [[aaa, fff, bbb, eee, ccc, ddd, ggg], 125], [[aaa, fff, bbb, ccc, eee, ddd, ggg], 120]]), binding("BestTour", [aaa, bbb, fff, ccc, eee, ddd, ggg]), binding("BestDistance", 75), binding("Optimal", [[aaa, bbb, fff, ccc, eee, ddd, ggg], 75])]),
                                        uses([
                                          proof(goal(ge(115, 75)), by(builtin(ge, 2))),
                                          proof(
                                            goal(min_distance_acc([[[aaa, ccc, eee, fff, bbb, ddd, ggg], 120], [[aaa, ccc, fff, eee, bbb, ddd, ggg], 110], [[aaa, ccc, fff, bbb, eee, ddd, ggg], 85], [[aaa, eee, ccc, bbb, fff, ddd, ggg], 140], [[aaa, eee, ccc, fff, bbb, ddd, ggg], 120], [[aaa, eee, bbb, ccc, fff, ddd, ggg], 130], [[aaa, eee, bbb, fff, ccc, ddd, ggg], 115], [[aaa, eee, fff, bbb, ccc, ddd, ggg], 140], [[aaa, eee, fff, ccc, bbb, ddd, ggg], 135], [[aaa, fff, ccc, eee, bbb, ddd, ggg], 120], [[aaa, fff, ccc, bbb, eee, ddd, ggg], 110], [[aaa, fff, eee, ccc, bbb, ddd, ggg], 145], [[aaa, fff, eee, bbb, ccc, ddd, ggg], 140], [[aaa, fff, bbb, eee, ccc, ddd, ggg], 125], [[aaa, fff, bbb, ccc, eee, ddd, ggg], 120]], [[aaa, bbb, fff, ccc, eee, ddd, ggg], 75], [[aaa, bbb, fff, ccc, eee, ddd, ggg], 75])), by(rule("traveling-salesman.pl", clause(30))),
                                            bindings([binding("_T", [aaa, ccc, eee, fff, bbb, ddd, ggg]), binding("D", 120), binding("Rest", [[[aaa, ccc, fff, eee, bbb, ddd, ggg], 110], [[aaa, ccc, fff, bbb, eee, ddd, ggg], 85], [[aaa, eee, ccc, bbb, fff, ddd, ggg], 140], [[aaa, eee, ccc, fff, bbb, ddd, ggg], 120], [[aaa, eee, bbb, ccc, fff, ddd, ggg], 130], [[aaa, eee, bbb, fff, ccc, ddd, ggg], 115], [[aaa, eee, fff, bbb, ccc, ddd, ggg], 140], [[aaa, eee, fff, ccc, bbb, ddd, ggg], 135], [[aaa, fff, ccc, eee, bbb, ddd, ggg], 120], [[aaa, fff, ccc, bbb, eee, ddd, ggg], 110], [[aaa, fff, eee, ccc, bbb, ddd, ggg], 145], [[aaa, fff, eee, bbb, ccc, ddd, ggg], 140], [[aaa, fff, bbb, eee, ccc, ddd, ggg], 125], [[aaa, fff, bbb, ccc, eee, ddd, ggg], 120]]), binding("BestTour", [aaa, bbb, fff, ccc, eee, ddd, ggg]), binding("BestDistance", 75), binding("Optimal", [[aaa, bbb, fff, ccc, eee, ddd, ggg], 75])]),
                                            uses([
                                              proof(goal(ge(120, 75)), by(builtin(ge, 2))),
                                              proof(
                                                goal(min_distance_acc([[[aaa, ccc, fff, eee, bbb, ddd, ggg], 110], [[aaa, ccc, fff, bbb, eee, ddd, ggg], 85], [[aaa, eee, ccc, bbb, fff, ddd, ggg], 140], [[aaa, eee, ccc, fff, bbb, ddd, ggg], 120], [[aaa, eee, bbb, ccc, fff, ddd, ggg], 130], [[aaa, eee, bbb, fff, ccc, ddd, ggg], 115], [[aaa, eee, fff, bbb, ccc, ddd, ggg], 140], [[aaa, eee, fff, ccc, bbb, ddd, ggg], 135], [[aaa, fff, ccc, eee, bbb, ddd, ggg], 120], [[aaa, fff, ccc, bbb, eee, ddd, ggg], 110], [[aaa, fff, eee, ccc, bbb, ddd, ggg], 145], [[aaa, fff, eee, bbb, ccc, ddd, ggg], 140], [[aaa, fff, bbb, eee, ccc, ddd, ggg], 125], [[aaa, fff, bbb, ccc, eee, ddd, ggg], 120]], [[aaa, bbb, fff, ccc, eee, ddd, ggg], 75], [[aaa, bbb, fff, ccc, eee, ddd, ggg], 75])), by(rule("traveling-salesman.pl", clause(30))),
                                                bindings([binding("_T", [aaa, ccc, fff, eee, bbb, ddd, ggg]), binding("D", 110), binding("Rest", [[[aaa, ccc, fff, bbb, eee, ddd, ggg], 85], [[aaa, eee, ccc, bbb, fff, ddd, ggg], 140], [[aaa, eee, ccc, fff, bbb, ddd, ggg], 120], [[aaa, eee, bbb, ccc, fff, ddd, ggg], 130], [[aaa, eee, bbb, fff, ccc, ddd, ggg], 115], [[aaa, eee, fff, bbb, ccc, ddd, ggg], 140], [[aaa, eee, fff, ccc, bbb, ddd, ggg], 135], [[aaa, fff, ccc, eee, bbb, ddd, ggg], 120], [[aaa, fff, ccc, bbb, eee, ddd, ggg], 110], [[aaa, fff, eee, ccc, bbb, ddd, ggg], 145], [[aaa, fff, eee, bbb, ccc, ddd, ggg], 140], [[aaa, fff, bbb, eee, ccc, ddd, ggg], 125], [[aaa, fff, bbb, ccc, eee, ddd, ggg], 120]]), binding("BestTour", [aaa, bbb, fff, ccc, eee, ddd, ggg]), binding("BestDistance", 75), binding("Optimal", [[aaa, bbb, fff, ccc, eee, ddd, ggg], 75])]),
                                                uses([
                                                  proof(goal(ge(110, 75)), by(builtin(ge, 2))),
                                                  proof(
                                                    goal(min_distance_acc([[[aaa, ccc, fff, bbb, eee, ddd, ggg], 85], [[aaa, eee, ccc, bbb, fff, ddd, ggg], 140], [[aaa, eee, ccc, fff, bbb, ddd, ggg], 120], [[aaa, eee, bbb, ccc, fff, ddd, ggg], 130], [[aaa, eee, bbb, fff, ccc, ddd, ggg], 115], [[aaa, eee, fff, bbb, ccc, ddd, ggg], 140], [[aaa, eee, fff, ccc, bbb, ddd, ggg], 135], [[aaa, fff, ccc, eee, bbb, ddd, ggg], 120], [[aaa, fff, ccc, bbb, eee, ddd, ggg], 110], [[aaa, fff, eee, ccc, bbb, ddd, ggg], 145], [[aaa, fff, eee, bbb, ccc, ddd, ggg], 140], [[aaa, fff, bbb, eee, ccc, ddd, ggg], 125], [[aaa, fff, bbb, ccc, eee, ddd, ggg], 120]], [[aaa, bbb, fff, ccc, eee, ddd, ggg], 75], [[aaa, bbb, fff, ccc, eee, ddd, ggg], 75])), by(rule("traveling-salesman.pl", clause(30))),
                                                    bindings([binding("_T", [aaa, ccc, fff, bbb, eee, ddd, ggg]), binding("D", 85), binding("Rest", [[[aaa, eee, ccc, bbb, fff, ddd, ggg], 140], [[aaa, eee, ccc, fff, bbb, ddd, ggg], 120], [[aaa, eee, bbb, ccc, fff, ddd, ggg], 130], [[aaa, eee, bbb, fff, ccc, ddd, ggg], 115], [[aaa, eee, fff, bbb, ccc, ddd, ggg], 140], [[aaa, eee, fff, ccc, bbb, ddd, ggg], 135], [[aaa, fff, ccc, eee, bbb, ddd, ggg], 120], [[aaa, fff, ccc, bbb, eee, ddd, ggg], 110], [[aaa, fff, eee, ccc, bbb, ddd, ggg], 145], [[aaa, fff, eee, bbb, ccc, ddd, ggg], 140], [[aaa, fff, bbb, eee, ccc, ddd, ggg], 125], [[aaa, fff, bbb, ccc, eee, ddd, ggg], 120]]), binding("BestTour", [aaa, bbb, fff, ccc, eee, ddd, ggg]), binding("BestDistance", 75), binding("Optimal", [[aaa, bbb, fff, ccc, eee, ddd, ggg], 75])]),
                                                    uses([
                                                      proof(goal(ge(85, 75)), by(builtin(ge, 2))),
                                                      proof(
                                                        goal(min_distance_acc([[[aaa, eee, ccc, bbb, fff, ddd, ggg], 140], [[aaa, eee, ccc, fff, bbb, ddd, ggg], 120], [[aaa, eee, bbb, ccc, fff, ddd, ggg], 130], [[aaa, eee, bbb, fff, ccc, ddd, ggg], 115], [[aaa, eee, fff, bbb, ccc, ddd, ggg], 140], [[aaa, eee, fff, ccc, bbb, ddd, ggg], 135], [[aaa, fff, ccc, eee, bbb, ddd, ggg], 120], [[aaa, fff, ccc, bbb, eee, ddd, ggg], 110], [[aaa, fff, eee, ccc, bbb, ddd, ggg], 145], [[aaa, fff, eee, bbb, ccc, ddd, ggg], 140], [[aaa, fff, bbb, eee, ccc, ddd, ggg], 125], [[aaa, fff, bbb, ccc, eee, ddd, ggg], 120]], [[aaa, bbb, fff, ccc, eee, ddd, ggg], 75], [[aaa, bbb, fff, ccc, eee, ddd, ggg], 75])), by(rule("traveling-salesman.pl", clause(30))),
                                                        bindings([binding("_T", [aaa, eee, ccc, bbb, fff, ddd, ggg]), binding("D", 140), binding("Rest", [[[aaa, eee, ccc, fff, bbb, ddd, ggg], 120], [[aaa, eee, bbb, ccc, fff, ddd, ggg], 130], [[aaa, eee, bbb, fff, ccc, ddd, ggg], 115], [[aaa, eee, fff, bbb, ccc, ddd, ggg], 140], [[aaa, eee, fff, ccc, bbb, ddd, ggg], 135], [[aaa, fff, ccc, eee, bbb, ddd, ggg], 120], [[aaa, fff, ccc, bbb, eee, ddd, ggg], 110], [[aaa, fff, eee, ccc, bbb, ddd, ggg], 145], [[aaa, fff, eee, bbb, ccc, ddd, ggg], 140], [[aaa, fff, bbb, eee, ccc, ddd, ggg], 125], [[aaa, fff, bbb, ccc, eee, ddd, ggg], 120]]), binding("BestTour", [aaa, bbb, fff, ccc, eee, ddd, ggg]), binding("BestDistance", 75), binding("Optimal", [[aaa, bbb, fff, ccc, eee, ddd, ggg], 75])]),
                                                        uses([
                                                          proof(goal(ge(140, 75)), by(builtin(ge, 2))),
                                                          proof(
                                                            goal(min_distance_acc([[[aaa, eee, ccc, fff, bbb, ddd, ggg], 120], [[aaa, eee, bbb, ccc, fff, ddd, ggg], 130], [[aaa, eee, bbb, fff, ccc, ddd, ggg], 115], [[aaa, eee, fff, bbb, ccc, ddd, ggg], 140], [[aaa, eee, fff, ccc, bbb, ddd, ggg], 135], [[aaa, fff, ccc, eee, bbb, ddd, ggg], 120], [[aaa, fff, ccc, bbb, eee, ddd, ggg], 110], [[aaa, fff, eee, ccc, bbb, ddd, ggg], 145], [[aaa, fff, eee, bbb, ccc, ddd, ggg], 140], [[aaa, fff, bbb, eee, ccc, ddd, ggg], 125], [[aaa, fff, bbb, ccc, eee, ddd, ggg], 120]], [[aaa, bbb, fff, ccc, eee, ddd, ggg], 75], [[aaa, bbb, fff, ccc, eee, ddd, ggg], 75])), by(rule("traveling-salesman.pl", clause(30))),
                                                            bindings([binding("_T", [aaa, eee, ccc, fff, bbb, ddd, ggg]), binding("D", 120), binding("Rest", [[[aaa, eee, bbb, ccc, fff, ddd, ggg], 130], [[aaa, eee, bbb, fff, ccc, ddd, ggg], 115], [[aaa, eee, fff, bbb, ccc, ddd, ggg], 140], [[aaa, eee, fff, ccc, bbb, ddd, ggg], 135], [[aaa, fff, ccc, eee, bbb, ddd, ggg], 120], [[aaa, fff, ccc, bbb, eee, ddd, ggg], 110], [[aaa, fff, eee, ccc, bbb, ddd, ggg], 145], [[aaa, fff, eee, bbb, ccc, ddd, ggg], 140], [[aaa, fff, bbb, eee, ccc, ddd, ggg], 125], [[aaa, fff, bbb, ccc, eee, ddd, ggg], 120]]), binding("BestTour", [aaa, bbb, fff, ccc, eee, ddd, ggg]), binding("BestDistance", 75), binding("Optimal", [[aaa, bbb, fff, ccc, eee, ddd, ggg], 75])]),
                                                            uses([
                                                              proof(goal(ge(120, 75)), by(builtin(ge, 2))),
                                                              proof(
                                                                goal(min_distance_acc([[[aaa, eee, bbb, ccc, fff, ddd, ggg], 130], [[aaa, eee, bbb, fff, ccc, ddd, ggg], 115], [[aaa, eee, fff, bbb, ccc, ddd, ggg], 140], [[aaa, eee, fff, ccc, bbb, ddd, ggg], 135], [[aaa, fff, ccc, eee, bbb, ddd, ggg], 120], [[aaa, fff, ccc, bbb, eee, ddd, ggg], 110], [[aaa, fff, eee, ccc, bbb, ddd, ggg], 145], [[aaa, fff, eee, bbb, ccc, ddd, ggg], 140], [[aaa, fff, bbb, eee, ccc, ddd, ggg], 125], [[aaa, fff, bbb, ccc, eee, ddd, ggg], 120]], [[aaa, bbb, fff, ccc, eee, ddd, ggg], 75], [[aaa, bbb, fff, ccc, eee, ddd, ggg], 75])), by(rule("traveling-salesman.pl", clause(30))),
                                                                bindings([binding("_T", [aaa, eee, bbb, ccc, fff, ddd, ggg]), binding("D", 130), binding("Rest", [[[aaa, eee, bbb, fff, ccc, ddd, ggg], 115], [[aaa, eee, fff, bbb, ccc, ddd, ggg], 140], [[aaa, eee, fff, ccc, bbb, ddd, ggg], 135], [[aaa, fff, ccc, eee, bbb, ddd, ggg], 120], [[aaa, fff, ccc, bbb, eee, ddd, ggg], 110], [[aaa, fff, eee, ccc, bbb, ddd, ggg], 145], [[aaa, fff, eee, bbb, ccc, ddd, ggg], 140], [[aaa, fff, bbb, eee, ccc, ddd, ggg], 125], [[aaa, fff, bbb, ccc, eee, ddd, ggg], 120]]), binding("BestTour", [aaa, bbb, fff, ccc, eee, ddd, ggg]), binding("BestDistance", 75), binding("Optimal", [[aaa, bbb, fff, ccc, eee, ddd, ggg], 75])]),
                                                                uses([
                                                                  proof(goal(ge(130, 75)), by(builtin(ge, 2))),
                                                                  proof(
                                                                    goal(min_distance_acc([[[aaa, eee, bbb, fff, ccc, ddd, ggg], 115], [[aaa, eee, fff, bbb, ccc, ddd, ggg], 140], [[aaa, eee, fff, ccc, bbb, ddd, ggg], 135], [[aaa, fff, ccc, eee, bbb, ddd, ggg], 120], [[aaa, fff, ccc, bbb, eee, ddd, ggg], 110], [[aaa, fff, eee, ccc, bbb, ddd, ggg], 145], [[aaa, fff, eee, bbb, ccc, ddd, ggg], 140], [[aaa, fff, bbb, eee, ccc, ddd, ggg], 125], [[aaa, fff, bbb, ccc, eee, ddd, ggg], 120]], [[aaa, bbb, fff, ccc, eee, ddd, ggg], 75], [[aaa, bbb, fff, ccc, eee, ddd, ggg], 75])), by(rule("traveling-salesman.pl", clause(30))),
                                                                    bindings([binding("_T", [aaa, eee, bbb, fff, ccc, ddd, ggg]), binding("D", 115), binding("Rest", [[[aaa, eee, fff, bbb, ccc, ddd, ggg], 140], [[aaa, eee, fff, ccc, bbb, ddd, ggg], 135], [[aaa, fff, ccc, eee, bbb, ddd, ggg], 120], [[aaa, fff, ccc, bbb, eee, ddd, ggg], 110], [[aaa, fff, eee, ccc, bbb, ddd, ggg], 145], [[aaa, fff, eee, bbb, ccc, ddd, ggg], 140], [[aaa, fff, bbb, eee, ccc, ddd, ggg], 125], [[aaa, fff, bbb, ccc, eee, ddd, ggg], 120]]), binding("BestTour", [aaa, bbb, fff, ccc, eee, ddd, ggg]), binding("BestDistance", 75), binding("Optimal", [[aaa, bbb, fff, ccc, eee, ddd, ggg], 75])]),
                                                                    uses([
                                                                      proof(goal(ge(115, 75)), by(builtin(ge, 2))),
                                                                      proof(
                                                                        goal(min_distance_acc([[[aaa, eee, fff, bbb, ccc, ddd, ggg], 140], [[aaa, eee, fff, ccc, bbb, ddd, ggg], 135], [[aaa, fff, ccc, eee, bbb, ddd, ggg], 120], [[aaa, fff, ccc, bbb, eee, ddd, ggg], 110], [[aaa, fff, eee, ccc, bbb, ddd, ggg], 145], [[aaa, fff, eee, bbb, ccc, ddd, ggg], 140], [[aaa, fff, bbb, eee, ccc, ddd, ggg], 125], [[aaa, fff, bbb, ccc, eee, ddd, ggg], 120]], [[aaa, bbb, fff, ccc, eee, ddd, ggg], 75], [[aaa, bbb, fff, ccc, eee, ddd, ggg], 75])), by(rule("traveling-salesman.pl", clause(30))),
                                                                        bindings([binding("_T", [aaa, eee, fff, bbb, ccc, ddd, ggg]), binding("D", 140), binding("Rest", [[[aaa, eee, fff, ccc, bbb, ddd, ggg], 135], [[aaa, fff, ccc, eee, bbb, ddd, ggg], 120], [[aaa, fff, ccc, bbb, eee, ddd, ggg], 110], [[aaa, fff, eee, ccc, bbb, ddd, ggg], 145], [[aaa, fff, eee, bbb, ccc, ddd, ggg], 140], [[aaa, fff, bbb, eee, ccc, ddd, ggg], 125], [[aaa, fff, bbb, ccc, eee, ddd, ggg], 120]]), binding("BestTour", [aaa, bbb, fff, ccc, eee, ddd, ggg]), binding("BestDistance", 75), binding("Optimal", [[aaa, bbb, fff, ccc, eee, ddd, ggg], 75])]),
                                                                        uses([
                                                                          proof(goal(ge(140, 75)), by(builtin(ge, 2))),
                                                                          proof(
                                                                            goal(min_distance_acc([[[aaa, eee, fff, ccc, bbb, ddd, ggg], 135], [[aaa, fff, ccc, eee, bbb, ddd, ggg], 120], [[aaa, fff, ccc, bbb, eee, ddd, ggg], 110], [[aaa, fff, eee, ccc, bbb, ddd, ggg], 145], [[aaa, fff, eee, bbb, ccc, ddd, ggg], 140], [[aaa, fff, bbb, eee, ccc, ddd, ggg], 125], [[aaa, fff, bbb, ccc, eee, ddd, ggg], 120]], [[aaa, bbb, fff, ccc, eee, ddd, ggg], 75], [[aaa, bbb, fff, ccc, eee, ddd, ggg], 75])), by(rule("traveling-salesman.pl", clause(30))),
                                                                            bindings([binding("_T", [aaa, eee, fff, ccc, bbb, ddd, ggg]), binding("D", 135), binding("Rest", [[[aaa, fff, ccc, eee, bbb, ddd, ggg], 120], [[aaa, fff, ccc, bbb, eee, ddd, ggg], 110], [[aaa, fff, eee, ccc, bbb, ddd, ggg], 145], [[aaa, fff, eee, bbb, ccc, ddd, ggg], 140], [[aaa, fff, bbb, eee, ccc, ddd, ggg], 125], [[aaa, fff, bbb, ccc, eee, ddd, ggg], 120]]), binding("BestTour", [aaa, bbb, fff, ccc, eee, ddd, ggg]), binding("BestDistance", 75), binding("Optimal", [[aaa, bbb, fff, ccc, eee, ddd, ggg], 75])]),
                                                                            uses([
                                                                              proof(goal(ge(135, 75)), by(builtin(ge, 2))),
                                                                              proof(
                                                                                goal(min_distance_acc([[[aaa, fff, ccc, eee, bbb, ddd, ggg], 120], [[aaa, fff, ccc, bbb, eee, ddd, ggg], 110], [[aaa, fff, eee, ccc, bbb, ddd, ggg], 145], [[aaa, fff, eee, bbb, ccc, ddd, ggg], 140], [[aaa, fff, bbb, eee, ccc, ddd, ggg], 125], [[aaa, fff, bbb, ccc, eee, ddd, ggg], 120]], [[aaa, bbb, fff, ccc, eee, ddd, ggg], 75], [[aaa, bbb, fff, ccc, eee, ddd, ggg], 75])), by(rule("traveling-salesman.pl", clause(30))),
                                                                                bindings([binding("_T", [aaa, fff, ccc, eee, bbb, ddd, ggg]), binding("D", 120), binding("Rest", [[[aaa, fff, ccc, bbb, eee, ddd, ggg], 110], [[aaa, fff, eee, ccc, bbb, ddd, ggg], 145], [[aaa, fff, eee, bbb, ccc, ddd, ggg], 140], [[aaa, fff, bbb, eee, ccc, ddd, ggg], 125], [[aaa, fff, bbb, ccc, eee, ddd, ggg], 120]]), binding("BestTour", [aaa, bbb, fff, ccc, eee, ddd, ggg]), binding("BestDistance", 75), binding("Optimal", [[aaa, bbb, fff, ccc, eee, ddd, ggg], 75])]),
                                                                                uses([
                                                                                  proof(goal(ge(120, 75)), by(builtin(ge, 2))),
                                                                                  proof(
                                                                                    goal(min_distance_acc([[[aaa, fff, ccc, bbb, eee, ddd, ggg], 110], [[aaa, fff, eee, ccc, bbb, ddd, ggg], 145], [[aaa, fff, eee, bbb, ccc, ddd, ggg], 140], [[aaa, fff, bbb, eee, ccc, ddd, ggg], 125], [[aaa, fff, bbb, ccc, eee, ddd, ggg], 120]], [[aaa, bbb, fff, ccc, eee, ddd, ggg], 75], [[aaa, bbb, fff, ccc, eee, ddd, ggg], 75])), by(rule("traveling-salesman.pl", clause(30))),
                                                                                    bindings([binding("_T", [aaa, fff, ccc, bbb, eee, ddd, ggg]), binding("D", 110), binding("Rest", [[[aaa, fff, eee, ccc, bbb, ddd, ggg], 145], [[aaa, fff, eee, bbb, ccc, ddd, ggg], 140], [[aaa, fff, bbb, eee, ccc, ddd, ggg], 125], [[aaa, fff, bbb, ccc, eee, ddd, ggg], 120]]), binding("BestTour", [aaa, bbb, fff, ccc, eee, ddd, ggg]), binding("BestDistance", 75), binding("Optimal", [[aaa, bbb, fff, ccc, eee, ddd, ggg], 75])]),
                                                                                    uses([
                                                                                      proof(goal(ge(110, 75)), by(builtin(ge, 2))),
                                                                                      proof(
                                                                                        goal(min_distance_acc([[[aaa, fff, eee, ccc, bbb, ddd, ggg], 145], [[aaa, fff, eee, bbb, ccc, ddd, ggg], 140], [[aaa, fff, bbb, eee, ccc, ddd, ggg], 125], [[aaa, fff, bbb, ccc, eee, ddd, ggg], 120]], [[aaa, bbb, fff, ccc, eee, ddd, ggg], 75], [[aaa, bbb, fff, ccc, eee, ddd, ggg], 75])), by(rule("traveling-salesman.pl", clause(30))),
                                                                                        bindings([binding("_T", [aaa, fff, eee, ccc, bbb, ddd, ggg]), binding("D", 145), binding("Rest", [[[aaa, fff, eee, bbb, ccc, ddd, ggg], 140], [[aaa, fff, bbb, eee, ccc, ddd, ggg], 125], [[aaa, fff, bbb, ccc, eee, ddd, ggg], 120]]), binding("BestTour", [aaa, bbb, fff, ccc, eee, ddd, ggg]), binding("BestDistance", 75), binding("Optimal", [[aaa, bbb, fff, ccc, eee, ddd, ggg], 75])]),
                                                                                        uses([
                                                                                          proof(goal(ge(145, 75)), by(builtin(ge, 2))),
                                                                                          proof(
                                                                                            goal(min_distance_acc([[[aaa, fff, eee, bbb, ccc, ddd, ggg], 140], [[aaa, fff, bbb, eee, ccc, ddd, ggg], 125], [[aaa, fff, bbb, ccc, eee, ddd, ggg], 120]], [[aaa, bbb, fff, ccc, eee, ddd, ggg], 75], [[aaa, bbb, fff, ccc, eee, ddd, ggg], 75])), by(rule("traveling-salesman.pl", clause(30))),
                                                                                            bindings([binding("_T", [aaa, fff, eee, bbb, ccc, ddd, ggg]), binding("D", 140), binding("Rest", [[[aaa, fff, bbb, eee, ccc, ddd, ggg], 125], [[aaa, fff, bbb, ccc, eee, ddd, ggg], 120]]), binding("BestTour", [aaa, bbb, fff, ccc, eee, ddd, ggg]), binding("BestDistance", 75), binding("Optimal", [[aaa, bbb, fff, ccc, eee, ddd, ggg], 75])]),
                                                                                            uses([
                                                                                              proof(goal(ge(140, 75)), by(builtin(ge, 2))),
                                                                                              proof(
                                                                                                goal(min_distance_acc([[[aaa, fff, bbb, eee, ccc, ddd, ggg], 125], [[aaa, fff, bbb, ccc, eee, ddd, ggg], 120]], [[aaa, bbb, fff, ccc, eee, ddd, ggg], 75], [[aaa, bbb, fff, ccc, eee, ddd, ggg], 75])), by(rule("traveling-salesman.pl", clause(30))),
                                                                                                bindings([binding("_T", [aaa, fff, bbb, eee, ccc, ddd, ggg]), binding("D", 125), binding("Rest", [[[aaa, fff, bbb, ccc, eee, ddd, ggg], 120]]), binding("BestTour", [aaa, bbb, fff, ccc, eee, ddd, ggg]), binding("BestDistance", 75), binding("Optimal", [[aaa, bbb, fff, ccc, eee, ddd, ggg], 75])]),
                                                                                                uses([
                                                                                                  proof(goal(ge(125, 75)), by(builtin(ge, 2))),
                                                                                                  proof(
                                                                                                    goal(min_distance_acc([[[aaa, fff, bbb, ccc, eee, ddd, ggg], 120]], [[aaa, bbb, fff, ccc, eee, ddd, ggg], 75], [[aaa, bbb, fff, ccc, eee, ddd, ggg], 75])), by(rule("traveling-salesman.pl", clause(30))),
                                                                                                    bindings([binding("_T", [aaa, fff, bbb, ccc, eee, ddd, ggg]), binding("D", 120), binding("Rest", []), binding("BestTour", [aaa, bbb, fff, ccc, eee, ddd, ggg]), binding("BestDistance", 75), binding("Optimal", [[aaa, bbb, fff, ccc, eee, ddd, ggg], 75])]),
                                                                                                    uses([
                                                                                                      proof(goal(ge(120, 75)), by(builtin(ge, 2))),
                                                                                                      proof(
                                                                                                        goal(min_distance_acc([], [[aaa, bbb, fff, ccc, eee, ddd, ggg], 75], [[aaa, bbb, fff, ccc, eee, ddd, ggg], 75])), by(fact("traveling-salesman.pl", clause(28))),
                                                                                                        bindings([binding("Best", [[aaa, bbb, fff, ccc, eee, ddd, ggg], 75])])
                                                                                                      )
                                                                                                    ])
                                                                                                  )
                                                                                                ])
                                                                                              )
                                                                                            ])
                                                                                          )
                                                                                        ])
                                                                                      )
                                                                                    ])
                                                                                  )
                                                                                ])
                                                                              )
                                                                            ])
                                                                          )
                                                                        ])
                                                                      )
                                                                    ])
                                                                  )
                                                                ])
                                                              )
                                                            ])
                                                          )
                                                        ])
                                                      )
                                                    ])
                                                  )
                                                ])
                                              )
                                            ])
                                          )
                                        ])
                                      )
                                    ])
                                  )
                                ])
                              )
                            ])
                          )
                        ])
                      )
                    ])
                  )
                ])
              )
            ])
          )
        ])
      )
    ])
  )
).

