# Eyelit result format 1
query(1, at(16, 1), [call(hanoi(3, left, right, center, ?v0))], [binding("moves", ?v0)]).
result(1, complete, 1).
answer(1, [binding("moves", [[left, right], [left, center], [right, center], [left, right], [center, left], [center, right], [left, right]])]).
why(1, [binding("moves", [[left, right], [left, center], [right, center], [left, right], [center, left], [center, right], [left, right]])], 21).
proof(1, hanoi(0, left, center, right, []), rule(3, at(8, 1)), []).
proof(2, hanoi(0, center, right, left, []), rule(3, at(8, 1)), []).
proof(3, append([], [[left, right]], [[left, right]]), rule(1, at(5, 1)), []).
proof(4, hanoi(1, left, right, center, [[left, right]]), rule(4, at(9, 1)), [compared(">", 1, 0), calculated(0, binary("-", value(1), value(1))), uses(1, hanoi(0, left, center, right, [])), uses(2, hanoi(0, center, right, left, [])), uses(3, append([], [[left, right]], [[left, right]]))]).
proof(5, hanoi(0, right, left, center, []), rule(3, at(8, 1)), []).
proof(6, append([], [[right, center]], [[right, center]]), rule(1, at(5, 1)), []).
proof(7, hanoi(1, right, center, left, [[right, center]]), rule(4, at(9, 1)), [compared(">", 1, 0), calculated(0, binary("-", value(1), value(1))), uses(5, hanoi(0, right, left, center, [])), uses(1, hanoi(0, left, center, right, [])), uses(6, append([], [[right, center]], [[right, center]]))]).
proof(8, append([], [[left, center], [right, center]], [[left, center], [right, center]]), rule(1, at(5, 1)), []).
proof(9, append([[left, right]], [[left, center], [right, center]], [[left, right], [left, center], [right, center]]), rule(2, at(6, 1)), [uses(8, append([], [[left, center], [right, center]], [[left, center], [right, center]]))]).
proof(10, hanoi(2, left, center, right, [[left, right], [left, center], [right, center]]), rule(4, at(9, 1)), [compared(">", 2, 0), calculated(1, binary("-", value(2), value(1))), uses(4, hanoi(1, left, right, center, [[left, right]])), uses(7, hanoi(1, right, center, left, [[right, center]])), uses(9, append([[left, right]], [[left, center], [right, center]], [[left, right], [left, center], [right, center]]))]).
proof(11, append([], [[center, left]], [[center, left]]), rule(1, at(5, 1)), []).
proof(12, hanoi(1, center, left, right, [[center, left]]), rule(4, at(9, 1)), [compared(">", 1, 0), calculated(0, binary("-", value(1), value(1))), uses(2, hanoi(0, center, right, left, [])), uses(5, hanoi(0, right, left, center, [])), uses(11, append([], [[center, left]], [[center, left]]))]).
proof(13, append([], [[center, right], [left, right]], [[center, right], [left, right]]), rule(1, at(5, 1)), []).
proof(14, append([[center, left]], [[center, right], [left, right]], [[center, left], [center, right], [left, right]]), rule(2, at(6, 1)), [uses(13, append([], [[center, right], [left, right]], [[center, right], [left, right]]))]).
proof(15, hanoi(2, center, right, left, [[center, left], [center, right], [left, right]]), rule(4, at(9, 1)), [compared(">", 2, 0), calculated(1, binary("-", value(2), value(1))), uses(12, hanoi(1, center, left, right, [[center, left]])), uses(4, hanoi(1, left, right, center, [[left, right]])), uses(14, append([[center, left]], [[center, right], [left, right]], [[center, left], [center, right], [left, right]]))]).
proof(16, append([], [[left, right], [center, left], [center, right], [left, right]], [[left, right], [center, left], [center, right], [left, right]]), rule(1, at(5, 1)), []).
proof(17, append([[right, center]], [[left, right], [center, left], [center, right], [left, right]], [[right, center], [left, right], [center, left], [center, right], [left, right]]), rule(2, at(6, 1)), [uses(16, append([], [[left, right], [center, left], [center, right], [left, right]], [[left, right], [center, left], [center, right], [left, right]]))]).
proof(18, append([[left, center], [right, center]], [[left, right], [center, left], [center, right], [left, right]], [[left, center], [right, center], [left, right], [center, left], [center, right], [left, right]]), rule(2, at(6, 1)), [uses(17, append([[right, center]], [[left, right], [center, left], [center, right], [left, right]], [[right, center], [left, right], [center, left], [center, right], [left, right]]))]).
proof(19, append([[left, right], [left, center], [right, center]], [[left, right], [center, left], [center, right], [left, right]], [[left, right], [left, center], [right, center], [left, right], [center, left], [center, right], [left, right]]), rule(2, at(6, 1)), [uses(18, append([[left, center], [right, center]], [[left, right], [center, left], [center, right], [left, right]], [[left, center], [right, center], [left, right], [center, left], [center, right], [left, right]]))]).
proof(20, hanoi(3, left, right, center, [[left, right], [left, center], [right, center], [left, right], [center, left], [center, right], [left, right]]), rule(4, at(9, 1)), [compared(">", 3, 0), calculated(2, binary("-", value(3), value(1))), uses(10, hanoi(2, left, center, right, [[left, right], [left, center], [right, center]])), uses(15, hanoi(2, center, right, left, [[center, left], [center, right], [left, right]])), uses(19, append([[left, right], [left, center], [right, center]], [[left, right], [center, left], [center, right], [left, right]], [[left, right], [left, center], [right, center], [left, right], [center, left], [center, right], [left, right]]))]).
proof(21, solution([[[left, right], [left, center], [right, center], [left, right], [center, left], [center, right], [left, right]]]), query, [uses(20, hanoi(3, left, right, center, [[left, right], [left, center], [right, center], [left, right], [center, left], [center, right], [left, right]]))]).
