# Eyelang result format 1
query(1, at(137, 1), [call(ranked_report(?v0))], [binding("risks", ?v0)]).
result(1, complete, 1).
answer(1, [binding("risks", [ranked(900, "C1", risk_delete_without_safeguards, 100, high_risk, high_severity, "Account removal is permitted without a notice constraint or duty to inform."), ranked(903, "C3", risk_share_without_consent, 97, high_risk, high_severity, "User data sharing is permitted without an explicit consent constraint."), ranked(915, "C2", risk_notice_too_short, 85, high_risk, high_severity, "Terms may change with less notice than the consumer requires."), ranked(930, "C4", risk_no_portability, 70, moderate_risk, moderate_severity, "Portability is restricted because exporting user data is prohibited.")])]).
why(1, [binding("risks", [ranked(900, "C1", risk_delete_without_safeguards, 100, high_risk, high_severity, "Account removal is permitted without a notice constraint or duty to inform."), ranked(903, "C3", risk_share_without_consent, 97, high_risk, high_severity, "User data sharing is permitted without an explicit consent constraint."), ranked(915, "C2", risk_notice_too_short, 85, high_risk, high_severity, "Terms may change with less notice than the consumer requires."), ranked(930, "C4", risk_no_portability, 70, moderate_risk, moderate_severity, "Portability is restricted because exporting user data is prohibited.")])], 42).
query(2, at(138, 1), [call(mitigation(?v0, ?v1, ?v2))], [binding("risk", ?v0), binding("measure", ?v1), binding("description", ?v2)]).
result(2, complete, 5).
answer(2, [binding("risk", risk_share_without_consent), binding("measure", mitigate_share_consent), binding("description", "Add an explicit-consent constraint before sharing data.")]).
why(2, [binding("risk", risk_share_without_consent), binding("measure", mitigate_share_consent), binding("description", "Add an explicit-consent constraint before sharing data.")], 62).
answer(2, [binding("risk", risk_no_portability), binding("measure", mitigate_portability), binding("description", "Permit data export or remove the export prohibition.")]).
why(2, [binding("risk", risk_no_portability), binding("measure", mitigate_portability), binding("description", "Permit data export or remove the export prohibition.")], 63).
answer(2, [binding("risk", risk_delete_without_safeguards), binding("measure", mitigate_delete_notice), binding("description", "Add a notice-days constraint before account removal.")]).
why(2, [binding("risk", risk_delete_without_safeguards), binding("measure", mitigate_delete_notice), binding("description", "Add a notice-days constraint before account removal.")], 67).
answer(2, [binding("risk", risk_delete_without_safeguards), binding("measure", mitigate_delete_inform), binding("description", "Add a duty to inform the consumer before account removal.")]).
why(2, [binding("risk", risk_delete_without_safeguards), binding("measure", mitigate_delete_inform), binding("description", "Add a duty to inform the consumer before account removal.")], 68).
answer(2, [binding("risk", risk_notice_too_short), binding("measure", mitigate_notice_too_short), binding("description", "Increase noticeDays to meet the consumer requirement.")]).
why(2, [binding("risk", risk_notice_too_short), binding("measure", mitigate_notice_too_short), binding("description", "Increase noticeDays to meet the consumer requirement.")], 72).
clause(2, has_need(consumer_example, need_data_cannot_be_removed), []).
clause(3, has_need(consumer_example, need_change_only_with_prior_notice), []).
clause(4, has_need(consumer_example, need_no_sharing_without_consent), []).
clause(5, has_need(consumer_example, need_data_portability), []).
clause(6, need(need_data_cannot_be_removed, 20), []).
clause(7, need(need_change_only_with_prior_notice, 15), []).
clause(8, need(need_no_sharing_without_consent, 12), []).
clause(9, need(need_data_portability, 10), []).
clause(10, minimum_notice_days(need_change_only_with_prior_notice, 14), []).
clause(11, agreement(agreement1, "Example Agreement", policy1), []).
clause(12, permission(policy1, perm_delete_account, remove_account, user_account, clause_c1), []).
clause(13, permission(policy1, perm_change_terms, change_terms, agreement_text, clause_c2), []).
clause(14, permission(policy1, perm_share_data, share_data, user_data, clause_c3), []).
clause(15, prohibition(policy1, prohibit_export_data, export_data, user_data, clause_c4), []).
clause(16, duty(perm_change_terms, inform), []).
clause(17, constraint(perm_change_terms, notice_days, gteq, 3), []).
clause(18, clause(clause_c1, "C1", "Provider may remove the user account and associated data at its discretion."), []).
clause(19, clause(clause_c2, "C2", "Provider may change terms by informing users at least 3 days in advance."), []).
clause(20, clause(clause_c3, "C3", "Provider may share user data with partners for business purposes."), []).
clause(21, clause(clause_c4, "C4", "Users are not permitted to export their data."), []).
clause(26, detected_risk(risk_delete_without_safeguards, source_delete_without_safeguards, legal_compliance_risk, unwanted_data_deletion, perm_delete_account, var("clause"), need_data_cannot_be_removed, var("raw"), "Account removal is permitted without a notice constraint or duty to inform."), [call(agreement(agreement1, var("title"), policy1)), call(has_need(consumer_example, need_data_cannot_be_removed)), call(need(need_data_cannot_be_removed, var("weight"))), call(permission(policy1, perm_delete_account, remove_account, user_account, var("clause"))), absent(has_notice_constraint(perm_delete_account)), absent(has_inform_duty(perm_delete_account)), calculate(var("raw"), binary("+", value(90), value(var("weight"))))]).
clause(27, detected_risk(risk_notice_too_short, source_notice_too_short, policy_risk, customer_confidence_loss, perm_change_terms, var("clause"), need_change_only_with_prior_notice, var("raw"), "Terms may change with less notice than the consumer requires."), [call(has_need(consumer_example, need_change_only_with_prior_notice)), call(need(need_change_only_with_prior_notice, var("weight"))), call(minimum_notice_days(need_change_only_with_prior_notice, var("required"))), call(permission(policy1, perm_change_terms, change_terms, agreement_text, var("clause"))), call(duty(perm_change_terms, inform)), call(constraint(perm_change_terms, notice_days, gteq, var("days"))), compare("<", var("days"), var("required")), calculate(var("raw"), binary("+", value(70), value(var("weight"))))]).
clause(28, detected_risk(risk_share_without_consent, source_share_without_consent, policy_risk, unwanted_disclosure_data, perm_share_data, var("clause"), need_no_sharing_without_consent, var("raw"), "User data sharing is permitted without an explicit consent constraint."), [call(has_need(consumer_example, need_no_sharing_without_consent)), call(need(need_no_sharing_without_consent, var("weight"))), call(permission(policy1, perm_share_data, share_data, user_data, var("clause"))), absent(has_explicit_consent(perm_share_data)), calculate(var("raw"), binary("+", value(85), value(var("weight"))))]).
clause(29, detected_risk(risk_no_portability, source_no_portability, policy_risk, customer_confidence_loss, prohibit_export_data, var("clause"), need_data_portability, var("raw"), "Portability is restricted because exporting user data is prohibited."), [call(has_need(consumer_example, need_data_portability)), call(need(need_data_portability, var("weight"))), call(prohibition(policy1, prohibit_export_data, export_data, user_data, var("clause"))), calculate(var("raw"), binary("+", value(60), value(var("weight"))))]).
clause(30, score(var("risk"), 100), [call(detected_risk(var("risk"), var("source"), var("source_type"), var("kind"), var("rule"), var("clause"), var("need"), var("raw"), var("why"))), compare(">", var("raw"), 100)]).
clause(31, score(var("risk"), var("raw")), [call(detected_risk(var("risk"), var("source"), var("source_type"), var("kind"), var("rule"), var("clause"), var("need"), var("raw"), var("why"))), compare("<=", var("raw"), 100)]).
clause(32, risk_level(var("risk"), high_risk, high_severity), [call(score(var("risk"), var("score"))), compare(">", var("score"), 79)]).
clause(33, risk_level(var("risk"), moderate_risk, moderate_severity), [call(score(var("risk"), var("score"))), compare(">=", var("score"), 50), compare("<", var("score"), 80)]).
clause(49, mitigation(risk_delete_without_safeguards, mitigate_delete_notice, "Add a notice-days constraint before account removal."), [call(detected_risk(risk_delete_without_safeguards, var("s"), var("st"), var("k"), var("r"), var("c"), var("n"), var("raw"), var("w")))]).
clause(50, mitigation(risk_delete_without_safeguards, mitigate_delete_inform, "Add a duty to inform the consumer before account removal."), [call(detected_risk(risk_delete_without_safeguards, var("s"), var("st"), var("k"), var("r"), var("c"), var("n"), var("raw"), var("w")))]).
clause(51, mitigation(risk_notice_too_short, mitigate_notice_too_short, "Increase noticeDays to meet the consumer requirement."), [call(detected_risk(risk_notice_too_short, var("s"), var("st"), var("k"), var("r"), var("c"), var("n"), var("raw"), var("w")))]).
clause(52, mitigation(risk_share_without_consent, mitigate_share_consent, "Add an explicit-consent constraint before sharing data."), [call(detected_risk(risk_share_without_consent, var("s"), var("st"), var("k"), var("r"), var("c"), var("n"), var("raw"), var("w")))]).
clause(53, mitigation(risk_no_portability, mitigate_portability, "Permit data export or remove the export prohibition."), [call(detected_risk(risk_no_portability, var("s"), var("st"), var("k"), var("r"), var("c"), var("n"), var("raw"), var("w")))]).
clause(54, ranked_report(var("ranked")), [collect(var("rows"), ranked(var("inverse"), var("clause_id"), var("risk"), var("score"), var("level"), var("severity"), var("why")), [call(detected_risk(var("risk"), var("source"), var("source_type"), var("kind"), var("rule"), var("clause"), var("need"), var("raw"), var("why"))), call(score(var("risk"), var("score"))), call(risk_level(var("risk"), var("level"), var("severity"))), call(clause(var("clause"), var("clause_id"), var("text"))), calculate(var("inverse"), binary("-", value(1000), value(var("score"))))]), call(sort(var("rows"), var("ranked")))]).
substitution(1, []).
proof(1, agreement(agreement1, "Example Agreement", policy1), rule(11, at(19, 1)), []).
substitution(2, []).
proof(2, has_need(consumer_example, need_change_only_with_prior_notice), rule(3, at(9, 1)), []).
substitution(3, []).
proof(3, has_need(consumer_example, need_no_sharing_without_consent), rule(4, at(10, 1)), []).
substitution(4, []).
proof(4, has_need(consumer_example, need_data_portability), rule(5, at(11, 1)), []).
substitution(5, []).
proof(5, has_need(consumer_example, need_data_cannot_be_removed), rule(2, at(8, 1)), []).
substitution(6, []).
proof(6, need(need_change_only_with_prior_notice, 15), rule(7, at(13, 1)), []).
substitution(7, []).
proof(7, need(need_no_sharing_without_consent, 12), rule(8, at(14, 1)), []).
substitution(8, []).
proof(8, need(need_data_portability, 10), rule(9, at(15, 1)), []).
substitution(9, []).
proof(9, need(need_data_cannot_be_removed, 20), rule(6, at(12, 1)), []).
substitution(10, []).
proof(10, minimum_notice_days(need_change_only_with_prior_notice, 14), rule(10, at(16, 1)), []).
substitution(11, []).
proof(11, permission(policy1, perm_share_data, share_data, user_data, clause_c3), rule(14, at(22, 1)), []).
substitution(12, []).
proof(12, prohibition(policy1, prohibit_export_data, export_data, user_data, clause_c4), rule(15, at(23, 1)), []).
substitution(13, [binding("clause", clause_c3), binding("raw", 97), binding("weight", 12)]).
proof(13, detected_risk(risk_share_without_consent, source_share_without_consent, policy_risk, unwanted_disclosure_data, perm_share_data, clause_c3, need_no_sharing_without_consent, 97, "User data sharing is permitted without an explicit consent constraint."), rule(28, at(64, 1)), [uses(3, has_need(consumer_example, need_no_sharing_without_consent)), uses(7, need(need_no_sharing_without_consent, 12)), uses(11, permission(policy1, perm_share_data, share_data, user_data, clause_c3)), absent(has_explicit_consent(perm_share_data), complete), calculated(97, binary("+", value(85), value(12)))]).
substitution(14, [binding("clause", clause_c4), binding("raw", 70), binding("weight", 10)]).
proof(14, detected_risk(risk_no_portability, source_no_portability, policy_risk, customer_confidence_loss, prohibit_export_data, clause_c4, need_data_portability, 70, "Portability is restricted because exporting user data is prohibited."), rule(29, at(75, 1)), [uses(4, has_need(consumer_example, need_data_portability)), uses(8, need(need_data_portability, 10)), uses(12, prohibition(policy1, prohibit_export_data, export_data, user_data, clause_c4)), calculated(70, binary("+", value(60), value(10)))]).
substitution(15, []).
proof(15, permission(policy1, perm_delete_account, remove_account, user_account, clause_c1), rule(12, at(20, 1)), []).
substitution(16, []).
proof(16, permission(policy1, perm_change_terms, change_terms, agreement_text, clause_c2), rule(13, at(21, 1)), []).
substitution(17, [binding("clause", clause_c1), binding("raw", 110), binding("title", "Example Agreement"), binding("weight", 20)]).
proof(17, detected_risk(risk_delete_without_safeguards, source_delete_without_safeguards, legal_compliance_risk, unwanted_data_deletion, perm_delete_account, clause_c1, need_data_cannot_be_removed, 110, "Account removal is permitted without a notice constraint or duty to inform."), rule(26, at(37, 1)), [uses(1, agreement(agreement1, "Example Agreement", policy1)), uses(5, has_need(consumer_example, need_data_cannot_be_removed)), uses(9, need(need_data_cannot_be_removed, 20)), uses(15, permission(policy1, perm_delete_account, remove_account, user_account, clause_c1)), absent(has_notice_constraint(perm_delete_account), complete), absent(has_inform_duty(perm_delete_account), complete), calculated(110, binary("+", value(90), value(20)))]).
substitution(18, []).
proof(18, duty(perm_change_terms, inform), rule(16, at(24, 1)), []).
substitution(19, [binding("clause", clause_c3), binding("raw", 97), binding("weight", 12)]).
proof(19, detected_risk(risk_share_without_consent, source_share_without_consent, policy_risk, unwanted_disclosure_data, perm_share_data, clause_c3, need_no_sharing_without_consent, 97, "User data sharing is permitted without an explicit consent constraint."), rule(28, at(64, 1)), [uses(3, has_need(consumer_example, need_no_sharing_without_consent)), uses(7, need(need_no_sharing_without_consent, 12)), uses(11, permission(policy1, perm_share_data, share_data, user_data, clause_c3)), absent(has_explicit_consent(perm_share_data), complete), calculated(97, binary("+", value(85), value(12)))]).
substitution(20, [binding("clause", clause_c4), binding("raw", 70), binding("weight", 10)]).
proof(20, detected_risk(risk_no_portability, source_no_portability, policy_risk, customer_confidence_loss, prohibit_export_data, clause_c4, need_data_portability, 70, "Portability is restricted because exporting user data is prohibited."), rule(29, at(75, 1)), [uses(4, has_need(consumer_example, need_data_portability)), uses(8, need(need_data_portability, 10)), uses(12, prohibition(policy1, prohibit_export_data, export_data, user_data, clause_c4)), calculated(70, binary("+", value(60), value(10)))]).
substitution(21, [binding("risk", risk_share_without_consent), binding("raw", 97), binding("source", source_share_without_consent), binding("source_type", policy_risk), binding("kind", unwanted_disclosure_data), binding("rule", perm_share_data), binding("clause", clause_c3), binding("need", need_no_sharing_without_consent), binding("why", "User data sharing is permitted without an explicit consent constraint.")]).
proof(21, score(risk_share_without_consent, 97), rule(31, at(86, 1)), [uses(19, detected_risk(risk_share_without_consent, source_share_without_consent, policy_risk, unwanted_disclosure_data, perm_share_data, clause_c3, need_no_sharing_without_consent, 97, "User data sharing is permitted without an explicit consent constraint.")), compared("<=", 97, 100)]).
substitution(22, [binding("risk", risk_no_portability), binding("raw", 70), binding("source", source_no_portability), binding("source_type", policy_risk), binding("kind", customer_confidence_loss), binding("rule", prohibit_export_data), binding("clause", clause_c4), binding("need", need_data_portability), binding("why", "Portability is restricted because exporting user data is prohibited.")]).
proof(22, score(risk_no_portability, 70), rule(31, at(86, 1)), [uses(20, detected_risk(risk_no_portability, source_no_portability, policy_risk, customer_confidence_loss, prohibit_export_data, clause_c4, need_data_portability, 70, "Portability is restricted because exporting user data is prohibited.")), compared("<=", 70, 100)]).
substitution(23, [binding("clause", clause_c1), binding("raw", 110), binding("title", "Example Agreement"), binding("weight", 20)]).
proof(23, detected_risk(risk_delete_without_safeguards, source_delete_without_safeguards, legal_compliance_risk, unwanted_data_deletion, perm_delete_account, clause_c1, need_data_cannot_be_removed, 110, "Account removal is permitted without a notice constraint or duty to inform."), rule(26, at(37, 1)), [uses(1, agreement(agreement1, "Example Agreement", policy1)), uses(5, has_need(consumer_example, need_data_cannot_be_removed)), uses(9, need(need_data_cannot_be_removed, 20)), uses(15, permission(policy1, perm_delete_account, remove_account, user_account, clause_c1)), absent(has_notice_constraint(perm_delete_account), complete), absent(has_inform_duty(perm_delete_account), complete), calculated(110, binary("+", value(90), value(20)))]).
substitution(24, []).
proof(24, constraint(perm_change_terms, notice_days, gteq, 3), rule(17, at(25, 1)), []).
substitution(25, [binding("risk", risk_delete_without_safeguards), binding("source", source_delete_without_safeguards), binding("source_type", legal_compliance_risk), binding("kind", unwanted_data_deletion), binding("rule", perm_delete_account), binding("clause", clause_c1), binding("need", need_data_cannot_be_removed), binding("raw", 110), binding("why", "Account removal is permitted without a notice constraint or duty to inform.")]).
proof(25, score(risk_delete_without_safeguards, 100), rule(30, at(85, 1)), [uses(23, detected_risk(risk_delete_without_safeguards, source_delete_without_safeguards, legal_compliance_risk, unwanted_data_deletion, perm_delete_account, clause_c1, need_data_cannot_be_removed, 110, "Account removal is permitted without a notice constraint or duty to inform.")), compared(">", 110, 100)]).
substitution(26, [binding("clause", clause_c2), binding("raw", 85), binding("weight", 15), binding("required", 14), binding("days", 3)]).
proof(26, detected_risk(risk_notice_too_short, source_notice_too_short, policy_risk, customer_confidence_loss, perm_change_terms, clause_c2, need_change_only_with_prior_notice, 85, "Terms may change with less notice than the consumer requires."), rule(27, at(50, 1)), [uses(2, has_need(consumer_example, need_change_only_with_prior_notice)), uses(6, need(need_change_only_with_prior_notice, 15)), uses(10, minimum_notice_days(need_change_only_with_prior_notice, 14)), uses(16, permission(policy1, perm_change_terms, change_terms, agreement_text, clause_c2)), uses(18, duty(perm_change_terms, inform)), uses(24, constraint(perm_change_terms, notice_days, gteq, 3)), compared("<", 3, 14), calculated(85, binary("+", value(70), value(15)))]).
substitution(27, [binding("risk", risk_share_without_consent), binding("score", 97)]).
proof(27, risk_level(risk_share_without_consent, high_risk, high_severity), rule(32, at(87, 1)), [uses(21, score(risk_share_without_consent, 97)), compared(">", 97, 79)]).
substitution(28, [binding("risk", risk_no_portability), binding("score", 70)]).
proof(28, risk_level(risk_no_portability, moderate_risk, moderate_severity), rule(33, at(88, 1)), [uses(22, score(risk_no_portability, 70)), compared(">=", 70, 50), compared("<", 70, 80)]).
substitution(29, []).
proof(29, clause(clause_c3, "C3", "Provider may share user data with partners for business purposes."), rule(20, at(28, 1)), []).
substitution(30, []).
proof(30, clause(clause_c4, "C4", "Users are not permitted to export their data."), rule(21, at(29, 1)), []).
substitution(31, [binding("risk", risk_delete_without_safeguards), binding("score", 100)]).
proof(31, risk_level(risk_delete_without_safeguards, high_risk, high_severity), rule(32, at(87, 1)), [uses(25, score(risk_delete_without_safeguards, 100)), compared(">", 100, 79)]).
substitution(32, [binding("inverse", 903), binding("clause_id", "C3"), binding("risk", risk_share_without_consent), binding("score", 97), binding("level", high_risk), binding("severity", high_severity), binding("why", "User data sharing is permitted without an explicit consent constraint.")]).
proof(32, solution([ranked(903, "C3", risk_share_without_consent, 97, high_risk, high_severity, "User data sharing is permitted without an explicit consent constraint.")]), query, [uses(13, detected_risk(risk_share_without_consent, source_share_without_consent, policy_risk, unwanted_disclosure_data, perm_share_data, clause_c3, need_no_sharing_without_consent, 97, "User data sharing is permitted without an explicit consent constraint.")), uses(21, score(risk_share_without_consent, 97)), uses(27, risk_level(risk_share_without_consent, high_risk, high_severity)), uses(29, clause(clause_c3, "C3", "Provider may share user data with partners for business purposes.")), calculated(903, binary("-", value(1000), value(97)))]).
substitution(33, [binding("inverse", 930), binding("clause_id", "C4"), binding("risk", risk_no_portability), binding("score", 70), binding("level", moderate_risk), binding("severity", moderate_severity), binding("why", "Portability is restricted because exporting user data is prohibited.")]).
proof(33, solution([ranked(930, "C4", risk_no_portability, 70, moderate_risk, moderate_severity, "Portability is restricted because exporting user data is prohibited.")]), query, [uses(14, detected_risk(risk_no_portability, source_no_portability, policy_risk, customer_confidence_loss, prohibit_export_data, clause_c4, need_data_portability, 70, "Portability is restricted because exporting user data is prohibited.")), uses(22, score(risk_no_portability, 70)), uses(28, risk_level(risk_no_portability, moderate_risk, moderate_severity)), uses(30, clause(clause_c4, "C4", "Users are not permitted to export their data.")), calculated(930, binary("-", value(1000), value(70)))]).
substitution(34, [binding("clause", clause_c2), binding("raw", 85), binding("weight", 15), binding("required", 14), binding("days", 3)]).
proof(34, detected_risk(risk_notice_too_short, source_notice_too_short, policy_risk, customer_confidence_loss, perm_change_terms, clause_c2, need_change_only_with_prior_notice, 85, "Terms may change with less notice than the consumer requires."), rule(27, at(50, 1)), [uses(2, has_need(consumer_example, need_change_only_with_prior_notice)), uses(6, need(need_change_only_with_prior_notice, 15)), uses(10, minimum_notice_days(need_change_only_with_prior_notice, 14)), uses(16, permission(policy1, perm_change_terms, change_terms, agreement_text, clause_c2)), uses(18, duty(perm_change_terms, inform)), uses(24, constraint(perm_change_terms, notice_days, gteq, 3)), compared("<", 3, 14), calculated(85, binary("+", value(70), value(15)))]).
substitution(35, []).
proof(35, clause(clause_c1, "C1", "Provider may remove the user account and associated data at its discretion."), rule(18, at(26, 1)), []).
substitution(36, [binding("risk", risk_notice_too_short), binding("raw", 85), binding("source", source_notice_too_short), binding("source_type", policy_risk), binding("kind", customer_confidence_loss), binding("rule", perm_change_terms), binding("clause", clause_c2), binding("need", need_change_only_with_prior_notice), binding("why", "Terms may change with less notice than the consumer requires.")]).
proof(36, score(risk_notice_too_short, 85), rule(31, at(86, 1)), [uses(34, detected_risk(risk_notice_too_short, source_notice_too_short, policy_risk, customer_confidence_loss, perm_change_terms, clause_c2, need_change_only_with_prior_notice, 85, "Terms may change with less notice than the consumer requires.")), compared("<=", 85, 100)]).
substitution(37, [binding("inverse", 900), binding("clause_id", "C1"), binding("risk", risk_delete_without_safeguards), binding("score", 100), binding("level", high_risk), binding("severity", high_severity), binding("why", "Account removal is permitted without a notice constraint or duty to inform.")]).
proof(37, solution([ranked(900, "C1", risk_delete_without_safeguards, 100, high_risk, high_severity, "Account removal is permitted without a notice constraint or duty to inform.")]), query, [uses(17, detected_risk(risk_delete_without_safeguards, source_delete_without_safeguards, legal_compliance_risk, unwanted_data_deletion, perm_delete_account, clause_c1, need_data_cannot_be_removed, 110, "Account removal is permitted without a notice constraint or duty to inform.")), uses(25, score(risk_delete_without_safeguards, 100)), uses(31, risk_level(risk_delete_without_safeguards, high_risk, high_severity)), uses(35, clause(clause_c1, "C1", "Provider may remove the user account and associated data at its discretion.")), calculated(900, binary("-", value(1000), value(100)))]).
substitution(38, [binding("risk", risk_notice_too_short), binding("score", 85)]).
proof(38, risk_level(risk_notice_too_short, high_risk, high_severity), rule(32, at(87, 1)), [uses(36, score(risk_notice_too_short, 85)), compared(">", 85, 79)]).
substitution(39, []).
proof(39, clause(clause_c2, "C2", "Provider may change terms by informing users at least 3 days in advance."), rule(19, at(27, 1)), []).
substitution(40, [binding("inverse", 915), binding("clause_id", "C2"), binding("risk", risk_notice_too_short), binding("score", 85), binding("level", high_risk), binding("severity", high_severity), binding("why", "Terms may change with less notice than the consumer requires.")]).
proof(40, solution([ranked(915, "C2", risk_notice_too_short, 85, high_risk, high_severity, "Terms may change with less notice than the consumer requires.")]), query, [uses(26, detected_risk(risk_notice_too_short, source_notice_too_short, policy_risk, customer_confidence_loss, perm_change_terms, clause_c2, need_change_only_with_prior_notice, 85, "Terms may change with less notice than the consumer requires.")), uses(36, score(risk_notice_too_short, 85)), uses(38, risk_level(risk_notice_too_short, high_risk, high_severity)), uses(39, clause(clause_c2, "C2", "Provider may change terms by informing users at least 3 days in advance.")), calculated(915, binary("-", value(1000), value(85)))]).
substitution(41, [binding("ranked", [ranked(900, "C1", risk_delete_without_safeguards, 100, high_risk, high_severity, "Account removal is permitted without a notice constraint or duty to inform."), ranked(903, "C3", risk_share_without_consent, 97, high_risk, high_severity, "User data sharing is permitted without an explicit consent constraint."), ranked(915, "C2", risk_notice_too_short, 85, high_risk, high_severity, "Terms may change with less notice than the consumer requires."), ranked(930, "C4", risk_no_portability, 70, moderate_risk, moderate_severity, "Portability is restricted because exporting user data is prohibited.")]), binding("rows", [ranked(900, "C1", risk_delete_without_safeguards, 100, high_risk, high_severity, "Account removal is permitted without a notice constraint or duty to inform."), ranked(903, "C3", risk_share_without_consent, 97, high_risk, high_severity, "User data sharing is permitted without an explicit consent constraint."), ranked(915, "C2", risk_notice_too_short, 85, high_risk, high_severity, "Terms may change with less notice than the consumer requires."), ranked(930, "C4", risk_no_portability, 70, moderate_risk, moderate_severity, "Portability is restricted because exporting user data is prohibited.")]), binding("inverse", ?v0), binding("clause_id", ?v1), binding("risk", ?v2), binding("score", ?v3), binding("level", ?v4), binding("severity", ?v5), binding("why", ?v6), binding("source", ?v7), binding("source_type", ?v8), binding("kind", ?v9), binding("rule", ?v10), binding("clause", ?v11), binding("need", ?v12), binding("raw", ?v13), binding("text", ?v14)]).
proof(41, ranked_report([ranked(900, "C1", risk_delete_without_safeguards, 100, high_risk, high_severity, "Account removal is permitted without a notice constraint or duty to inform."), ranked(903, "C3", risk_share_without_consent, 97, high_risk, high_severity, "User data sharing is permitted without an explicit consent constraint."), ranked(915, "C2", risk_notice_too_short, 85, high_risk, high_severity, "Terms may change with less notice than the consumer requires."), ranked(930, "C4", risk_no_portability, 70, moderate_risk, moderate_severity, "Portability is restricted because exporting user data is prohibited.")]), rule(54, at(127, 1)), [collected([ranked(900, "C1", risk_delete_without_safeguards, 100, high_risk, high_severity, "Account removal is permitted without a notice constraint or duty to inform."), ranked(903, "C3", risk_share_without_consent, 97, high_risk, high_severity, "User data sharing is permitted without an explicit consent constraint."), ranked(915, "C2", risk_notice_too_short, 85, high_risk, high_severity, "Terms may change with less notice than the consumer requires."), ranked(930, "C4", risk_no_portability, 70, moderate_risk, moderate_severity, "Portability is restricted because exporting user data is prohibited.")], ranked(?v0, ?v1, ?v2, ?v3, ?v4, ?v5, ?v6), [call(detected_risk(?v2, ?v7, ?v8, ?v9, ?v10, ?v11, ?v12, ?v13, ?v6)), call(score(?v2, ?v3)), call(risk_level(?v2, ?v4, ?v5)), call(clause(?v11, ?v1, ?v14)), calculate(?v0, binary("-", value(1000), value(?v3)))], [32, 33, 37, 40], complete), builtin(sort([ranked(900, "C1", risk_delete_without_safeguards, 100, high_risk, high_severity, "Account removal is permitted without a notice constraint or duty to inform."), ranked(903, "C3", risk_share_without_consent, 97, high_risk, high_severity, "User data sharing is permitted without an explicit consent constraint."), ranked(915, "C2", risk_notice_too_short, 85, high_risk, high_severity, "Terms may change with less notice than the consumer requires."), ranked(930, "C4", risk_no_portability, 70, moderate_risk, moderate_severity, "Portability is restricted because exporting user data is prohibited.")], [ranked(900, "C1", risk_delete_without_safeguards, 100, high_risk, high_severity, "Account removal is permitted without a notice constraint or duty to inform."), ranked(903, "C3", risk_share_without_consent, 97, high_risk, high_severity, "User data sharing is permitted without an explicit consent constraint."), ranked(915, "C2", risk_notice_too_short, 85, high_risk, high_severity, "Terms may change with less notice than the consumer requires."), ranked(930, "C4", risk_no_portability, 70, moderate_risk, moderate_severity, "Portability is restricted because exporting user data is prohibited.")]))]).
substitution(42, [binding("risks", [ranked(900, "C1", risk_delete_without_safeguards, 100, high_risk, high_severity, "Account removal is permitted without a notice constraint or duty to inform."), ranked(903, "C3", risk_share_without_consent, 97, high_risk, high_severity, "User data sharing is permitted without an explicit consent constraint."), ranked(915, "C2", risk_notice_too_short, 85, high_risk, high_severity, "Terms may change with less notice than the consumer requires."), ranked(930, "C4", risk_no_portability, 70, moderate_risk, moderate_severity, "Portability is restricted because exporting user data is prohibited.")])]).
proof(42, solution([[ranked(900, "C1", risk_delete_without_safeguards, 100, high_risk, high_severity, "Account removal is permitted without a notice constraint or duty to inform."), ranked(903, "C3", risk_share_without_consent, 97, high_risk, high_severity, "User data sharing is permitted without an explicit consent constraint."), ranked(915, "C2", risk_notice_too_short, 85, high_risk, high_severity, "Terms may change with less notice than the consumer requires."), ranked(930, "C4", risk_no_portability, 70, moderate_risk, moderate_severity, "Portability is restricted because exporting user data is prohibited.")]]), query, [uses(41, ranked_report([ranked(900, "C1", risk_delete_without_safeguards, 100, high_risk, high_severity, "Account removal is permitted without a notice constraint or duty to inform."), ranked(903, "C3", risk_share_without_consent, 97, high_risk, high_severity, "User data sharing is permitted without an explicit consent constraint."), ranked(915, "C2", risk_notice_too_short, 85, high_risk, high_severity, "Terms may change with less notice than the consumer requires."), ranked(930, "C4", risk_no_portability, 70, moderate_risk, moderate_severity, "Portability is restricted because exporting user data is prohibited.")]))]).
substitution(43, []).
proof(43, agreement(agreement1, "Example Agreement", policy1), rule(11, at(19, 1)), []).
substitution(44, []).
proof(44, has_need(consumer_example, need_change_only_with_prior_notice), rule(3, at(9, 1)), []).
substitution(45, []).
proof(45, has_need(consumer_example, need_no_sharing_without_consent), rule(4, at(10, 1)), []).
substitution(46, []).
proof(46, has_need(consumer_example, need_data_portability), rule(5, at(11, 1)), []).
substitution(47, []).
proof(47, has_need(consumer_example, need_data_cannot_be_removed), rule(2, at(8, 1)), []).
substitution(48, []).
proof(48, need(need_change_only_with_prior_notice, 15), rule(7, at(13, 1)), []).
substitution(49, []).
proof(49, need(need_no_sharing_without_consent, 12), rule(8, at(14, 1)), []).
substitution(50, []).
proof(50, need(need_data_portability, 10), rule(9, at(15, 1)), []).
substitution(51, []).
proof(51, need(need_data_cannot_be_removed, 20), rule(6, at(12, 1)), []).
substitution(52, []).
proof(52, minimum_notice_days(need_change_only_with_prior_notice, 14), rule(10, at(16, 1)), []).
substitution(53, []).
proof(53, permission(policy1, perm_share_data, share_data, user_data, clause_c3), rule(14, at(22, 1)), []).
substitution(54, []).
proof(54, prohibition(policy1, prohibit_export_data, export_data, user_data, clause_c4), rule(15, at(23, 1)), []).
substitution(55, [binding("clause", clause_c3), binding("raw", 97), binding("weight", 12)]).
proof(55, detected_risk(risk_share_without_consent, source_share_without_consent, policy_risk, unwanted_disclosure_data, perm_share_data, clause_c3, need_no_sharing_without_consent, 97, "User data sharing is permitted without an explicit consent constraint."), rule(28, at(64, 1)), [uses(45, has_need(consumer_example, need_no_sharing_without_consent)), uses(49, need(need_no_sharing_without_consent, 12)), uses(53, permission(policy1, perm_share_data, share_data, user_data, clause_c3)), absent(has_explicit_consent(perm_share_data), complete), calculated(97, binary("+", value(85), value(12)))]).
substitution(56, [binding("clause", clause_c4), binding("raw", 70), binding("weight", 10)]).
proof(56, detected_risk(risk_no_portability, source_no_portability, policy_risk, customer_confidence_loss, prohibit_export_data, clause_c4, need_data_portability, 70, "Portability is restricted because exporting user data is prohibited."), rule(29, at(75, 1)), [uses(46, has_need(consumer_example, need_data_portability)), uses(50, need(need_data_portability, 10)), uses(54, prohibition(policy1, prohibit_export_data, export_data, user_data, clause_c4)), calculated(70, binary("+", value(60), value(10)))]).
substitution(57, []).
proof(57, permission(policy1, perm_delete_account, remove_account, user_account, clause_c1), rule(12, at(20, 1)), []).
substitution(58, []).
proof(58, permission(policy1, perm_change_terms, change_terms, agreement_text, clause_c2), rule(13, at(21, 1)), []).
substitution(59, [binding("s", source_share_without_consent), binding("st", policy_risk), binding("k", unwanted_disclosure_data), binding("r", perm_share_data), binding("c", clause_c3), binding("n", need_no_sharing_without_consent), binding("raw", 97), binding("w", "User data sharing is permitted without an explicit consent constraint.")]).
proof(59, mitigation(risk_share_without_consent, mitigate_share_consent, "Add an explicit-consent constraint before sharing data."), rule(52, at(119, 1)), [uses(55, detected_risk(risk_share_without_consent, source_share_without_consent, policy_risk, unwanted_disclosure_data, perm_share_data, clause_c3, need_no_sharing_without_consent, 97, "User data sharing is permitted without an explicit consent constraint."))]).
substitution(60, [binding("s", source_no_portability), binding("st", policy_risk), binding("k", customer_confidence_loss), binding("r", prohibit_export_data), binding("c", clause_c4), binding("n", need_data_portability), binding("raw", 70), binding("w", "Portability is restricted because exporting user data is prohibited.")]).
proof(60, mitigation(risk_no_portability, mitigate_portability, "Permit data export or remove the export prohibition."), rule(53, at(122, 1)), [uses(56, detected_risk(risk_no_portability, source_no_portability, policy_risk, customer_confidence_loss, prohibit_export_data, clause_c4, need_data_portability, 70, "Portability is restricted because exporting user data is prohibited."))]).
substitution(61, [binding("clause", clause_c1), binding("raw", 110), binding("title", "Example Agreement"), binding("weight", 20)]).
proof(61, detected_risk(risk_delete_without_safeguards, source_delete_without_safeguards, legal_compliance_risk, unwanted_data_deletion, perm_delete_account, clause_c1, need_data_cannot_be_removed, 110, "Account removal is permitted without a notice constraint or duty to inform."), rule(26, at(37, 1)), [uses(43, agreement(agreement1, "Example Agreement", policy1)), uses(47, has_need(consumer_example, need_data_cannot_be_removed)), uses(51, need(need_data_cannot_be_removed, 20)), uses(57, permission(policy1, perm_delete_account, remove_account, user_account, clause_c1)), absent(has_notice_constraint(perm_delete_account), complete), absent(has_inform_duty(perm_delete_account), complete), calculated(110, binary("+", value(90), value(20)))]).
substitution(62, [binding("risk", risk_share_without_consent), binding("measure", mitigate_share_consent), binding("description", "Add an explicit-consent constraint before sharing data.")]).
proof(62, solution([risk_share_without_consent, mitigate_share_consent, "Add an explicit-consent constraint before sharing data."]), query, [uses(59, mitigation(risk_share_without_consent, mitigate_share_consent, "Add an explicit-consent constraint before sharing data."))]).
substitution(63, [binding("risk", risk_no_portability), binding("measure", mitigate_portability), binding("description", "Permit data export or remove the export prohibition.")]).
proof(63, solution([risk_no_portability, mitigate_portability, "Permit data export or remove the export prohibition."]), query, [uses(60, mitigation(risk_no_portability, mitigate_portability, "Permit data export or remove the export prohibition."))]).
substitution(64, [binding("s", source_delete_without_safeguards), binding("st", legal_compliance_risk), binding("k", unwanted_data_deletion), binding("r", perm_delete_account), binding("c", clause_c1), binding("n", need_data_cannot_be_removed), binding("raw", 110), binding("w", "Account removal is permitted without a notice constraint or duty to inform.")]).
proof(64, mitigation(risk_delete_without_safeguards, mitigate_delete_notice, "Add a notice-days constraint before account removal."), rule(49, at(110, 1)), [uses(61, detected_risk(risk_delete_without_safeguards, source_delete_without_safeguards, legal_compliance_risk, unwanted_data_deletion, perm_delete_account, clause_c1, need_data_cannot_be_removed, 110, "Account removal is permitted without a notice constraint or duty to inform."))]).
substitution(65, [binding("s", source_delete_without_safeguards), binding("st", legal_compliance_risk), binding("k", unwanted_data_deletion), binding("r", perm_delete_account), binding("c", clause_c1), binding("n", need_data_cannot_be_removed), binding("raw", 110), binding("w", "Account removal is permitted without a notice constraint or duty to inform.")]).
proof(65, mitigation(risk_delete_without_safeguards, mitigate_delete_inform, "Add a duty to inform the consumer before account removal."), rule(50, at(113, 1)), [uses(61, detected_risk(risk_delete_without_safeguards, source_delete_without_safeguards, legal_compliance_risk, unwanted_data_deletion, perm_delete_account, clause_c1, need_data_cannot_be_removed, 110, "Account removal is permitted without a notice constraint or duty to inform."))]).
substitution(66, []).
proof(66, duty(perm_change_terms, inform), rule(16, at(24, 1)), []).
substitution(67, [binding("risk", risk_delete_without_safeguards), binding("measure", mitigate_delete_notice), binding("description", "Add a notice-days constraint before account removal.")]).
proof(67, solution([risk_delete_without_safeguards, mitigate_delete_notice, "Add a notice-days constraint before account removal."]), query, [uses(64, mitigation(risk_delete_without_safeguards, mitigate_delete_notice, "Add a notice-days constraint before account removal."))]).
substitution(68, [binding("risk", risk_delete_without_safeguards), binding("measure", mitigate_delete_inform), binding("description", "Add a duty to inform the consumer before account removal.")]).
proof(68, solution([risk_delete_without_safeguards, mitigate_delete_inform, "Add a duty to inform the consumer before account removal."]), query, [uses(65, mitigation(risk_delete_without_safeguards, mitigate_delete_inform, "Add a duty to inform the consumer before account removal."))]).
substitution(69, []).
proof(69, constraint(perm_change_terms, notice_days, gteq, 3), rule(17, at(25, 1)), []).
substitution(70, [binding("clause", clause_c2), binding("raw", 85), binding("weight", 15), binding("required", 14), binding("days", 3)]).
proof(70, detected_risk(risk_notice_too_short, source_notice_too_short, policy_risk, customer_confidence_loss, perm_change_terms, clause_c2, need_change_only_with_prior_notice, 85, "Terms may change with less notice than the consumer requires."), rule(27, at(50, 1)), [uses(44, has_need(consumer_example, need_change_only_with_prior_notice)), uses(48, need(need_change_only_with_prior_notice, 15)), uses(52, minimum_notice_days(need_change_only_with_prior_notice, 14)), uses(58, permission(policy1, perm_change_terms, change_terms, agreement_text, clause_c2)), uses(66, duty(perm_change_terms, inform)), uses(69, constraint(perm_change_terms, notice_days, gteq, 3)), compared("<", 3, 14), calculated(85, binary("+", value(70), value(15)))]).
substitution(71, [binding("s", source_notice_too_short), binding("st", policy_risk), binding("k", customer_confidence_loss), binding("r", perm_change_terms), binding("c", clause_c2), binding("n", need_change_only_with_prior_notice), binding("raw", 85), binding("w", "Terms may change with less notice than the consumer requires.")]).
proof(71, mitigation(risk_notice_too_short, mitigate_notice_too_short, "Increase noticeDays to meet the consumer requirement."), rule(51, at(116, 1)), [uses(70, detected_risk(risk_notice_too_short, source_notice_too_short, policy_risk, customer_confidence_loss, perm_change_terms, clause_c2, need_change_only_with_prior_notice, 85, "Terms may change with less notice than the consumer requires."))]).
substitution(72, [binding("risk", risk_notice_too_short), binding("measure", mitigate_notice_too_short), binding("description", "Increase noticeDays to meet the consumer requirement.")]).
proof(72, solution([risk_notice_too_short, mitigate_notice_too_short, "Increase noticeDays to meet the consumer requirement."]), query, [uses(71, mitigation(risk_notice_too_short, mitigate_notice_too_short, "Increase noticeDays to meet the consumer requirement."))]).
